package template

import "strings"

// GetAgentGuide returns FLASH.md — a complete, self-contained reference an AI
// agent can read to understand and drive FlashORM in this project. The content
// is tailored to the database and language detected at init time and embeds the
// exact schema/queries that were scaffolded, so the guide always matches the
// code on disk.
//
// Key design decisions:
//   - The guide uses §...§ as a backtick placeholder (raw string literals
//     cannot contain backticks) and @@TOKEN@@ for DB-specific values.
//   - Generated code location is explained as "read from flash.toml [gen.*].out"
//     not hardcoded to "flash_gen", because users can change it.
func (pt *ProjectTemplate) GetAgentGuide() string {
	cfg := dbConfigs[pt.DatabaseType]

	ext := ".sql"
	schemaDir := "db/schema"
	if pt.DatabaseType == ScyllaDB {
		ext = ".cql"
	}

	guide := agentGuideTemplate
	language, languageGuide := pt.agentLanguageGuide()

	replacements := []struct{ from, to string }{
		{"@@PROVIDER@@", cfg.provider},
		{"@@PARAM@@", cfg.queryParam},
		{"@@ENV@@", cfg.envExample},
		{"@@EXT@@", ext},
		{"@@SCHEMADIR@@", schemaDir},
		{"@@PROVIDERLIST@@", "postgresql | mysql | sqlite | clickhouse | scylla"},
		{"@@SCHEMA@@", strings.TrimRight(pt.GetSchema(), "\n")},
		{"@@QUERIES@@", strings.TrimRight(pt.GetQueries(), "\n")},
		{"@@DRIVERS@@", pt.getDriverHeaderComment()},
		{"@@LANGUAGE@@", language},
		{"@@LANGGUIDE@@", languageGuide},
	}
	for _, r := range replacements {
		guide = strings.ReplaceAll(guide, r.from, r.to)
	}
	guide = strings.ReplaceAll(guide, "§", "`")
	return guide
}

// agentGuideTemplate is the raw FLASH.md template.
// § is used as a backtick placeholder; @@TOKEN@@ marks DB-specific injections.
const agentGuideTemplate = `# FLASH.md — FlashORM Agent Guide

> Auto-generated by §flash init§. This file is the single source of truth for
> using FlashORM in this project. Written for AI coding agents: read it fully
> before making any changes.
>
> **This project's database:** §@@PROVIDER@@§
> **Query parameter style:** §@@PARAM@@§
> **Schema file extension:** §@@EXT@@§

---

## 1. What FlashORM is

FlashORM is a **SQL-first, type-safe ORM and code generator**. You write plain
SQL; Flash generates type-safe client code from it for **Go, TypeScript,
JavaScript, Python, Kotlin, Java, and Rust**.

Two inputs drive everything:

- §@@SCHEMADIR@@/§ — table definitions (DDL, §@@EXT@@§ files).
- §db/queries/§ — named queries, each tagged with §-- name:§.

§flash gen§ reads both and emits type-safe functions and structs.

> ⚠️ **Never edit generated files.** They are overwritten on every §flash gen§.
> Edit the §@@EXT@@§ sources, then re-run §flash gen§.

---

## 2. Where generated code lives

The output directory is configured in §flash.toml§ under §[gen.*].out§.
**Do not assume it is always §flash_gen/§** — users can change it.

To find the actual output path:

1. Read §flash.toml§ in the project root.
2. Find the enabled §[gen.*]§ block (e.g. §[gen.go]§, §[gen.rust]§).
3. The §out§ field gives the directory. If §out§ is absent, default is §flash_gen§.

Example:

§§§toml
[gen.go]
enabled = true
out = "internal/db/flash_gen"   # ← the real output directory
§§§

§§§toml
[gen.rust]
enabled = true
out = "src/db"                  # ← generated .rs files go here
§§§

When §flash gen§ runs it prints §Output: <dir>/§ so you can confirm the path.

---

## 3. Project layout

§§§
flash.toml            # config: provider, codegen targets, cache settings
@@SCHEMADIR@@/            # schema DDL — CREATE TABLE ... (edit these)
  schema@@EXT@@
db/queries/           # named SQL queries (edit these)
  users@@EXT@@
db/migrations/        # auto-generated migration files — do not edit
.env                  # DATABASE_URL and secrets (never commit)
<gen.*.out>/          # generated type-safe code — do not edit
§§§

---

## 4. Everyday workflow

§§§bash
# 1. (already done) flash init --@@PROVIDER@@
# 2. Edit schema
edit @@SCHEMADIR@@/schema@@EXT@@
# 3. Create and apply migration
flash migrate "describe change"
flash apply
# 4. Write queries
edit db/queries/users@@EXT@@
# 5. Generate code (check flash.toml for the output dir)
flash gen
# 6. (optional) visual editor
flash studio
§§§

Fast iteration on a fresh dev DB: §flash apply§ creates tables directly from
schema without migrations. For tracked incremental changes always use
§flash migrate "<msg>"§ + §flash apply§.

Re-run §flash gen§ after every §@@EXT@@§ file change.

---

## 5. CLI command reference

| Command | What it does | Key flags |
|---|---|---|
| §flash init [name]§ | Scaffold a new project | §--@@PROVIDER@@§, §--sqlite§, §--mysql§, §--clickhouse§, §--scylla§ |
| §flash migrate <name>§ | Create migration from schema diff | |
| §flash apply§ | Apply pending migrations | §--force§, §--db <name>§ |
| §flash down [id]§ | Roll back migration(s) | |
| §flash status§ | Show applied/pending | §--db <name>§ |
| §flash pull§ | Reverse-engineer schema from existing DB | |
| §flash reset§ | Drop & recreate (dev only) | §--force§ |
| §flash raw <sql-or-file>§ | Execute raw SQL | |
| §flash gen§ | Generate type-safe code | §-f§ force rebuild, §--db <name>§ |
| §flash export§ | Export tables | §--csv§, §--sqlite§ |
| §flash seed [tables...]§ | Insert fake test data | §--count N§, §--truncate§ |
| §flash branch [name]§ | List/create/delete schema branches | |
| §flash checkout <branch>§ | Switch schema branch | |
| §flash studio [URL]§ | Visual editor (SQL / MongoDB / Redis) | §--db <name>§ |
| §flash dblist§ | List configured databases | |
| §flash issues§ | File a bug or feature report | |
| §flash update§ | Update plugins and binary | |

---

## 6. flash.toml reference

§§§toml
version = "2"
schema_dir = "@@SCHEMADIR@@"        # DDL directory
queries    = "db/queries/"          # query directory
migrations_path = "db/migrations"
export_path     = "db/export"
env_path        = ""                # extra .env file path (optional)
json_path       = ""                # dir with .json defs for @json columns

[database]
provider = "@@PROVIDER@@"           # @@PROVIDERLIST@@
url_env  = "DATABASE_URL"           # env var with connection string

# ── Code generation — enable one or more targets ──────────────────────────

[gen.go]
enabled = true
out     = "flash_gen"               # output directory (change freely)
# driver = "pgx"                    # or "database/sql"

# [gen.js]
# enabled = true
# out     = "flash_gen"
# driver  = "pg"

# [gen.python]
# enabled = true
# out     = "flash_gen"
# async   = true
# driver  = "asyncpg"

# [gen.rust]
# enabled = true
# out     = "src/flash_gen"
# driver  = "sqlx"
# macros  = false                   # true = sqlx compile-time checked macros

# [gen.kotlin]
# enabled = true
# out     = "src/main/kotlin/com/example/flashgen"
# package = "com.example.flashgen"
# driver  = "jdbc"

# [gen.java]
# enabled = true
# out     = "src/main/java/com/example/flashgen"
# package = "com.example.flashgen"
# driver  = "jdbc"

# ── Query result caching (Redis) — off by default ────────────────────────

[cache]
enabled       = false
redis_url_env = "REDIS_URL"
default_ttl   = "5m"
prefix        = "flash"
§§§

**Multi-database:** replace §[database]§ with §[[databases]]§ blocks, each with
its own §name§, §provider§, §url_env§, and §[databases.gen.*]§. Target one with
§--db <name>§ or set §default = true§.

§§§toml
[[databases]]
name     = "main"
provider = "@@PROVIDER@@"
url_env  = "MAIN_DATABASE_URL"
default  = true

[[databases]]
name     = "analytics"
provider = "clickhouse"
url_env  = "ANALYTICS_URL"
§§§

---

## 7. Database connection

The connection string lives **only in the env var** named by §url_env§. Flash
reads §.env§ automatically (also §.env.local§, §.env.<name>§ via §--env <name>§).

This project:

§§§
DATABASE_URL=@@ENV@@
§§§

Connection string formats:

| Provider | Example |
|---|---|
| postgresql | §postgres://user:pass@localhost:5432/dbname§ |
| mysql | §mysql://user:pass@localhost:3306/dbname§ |
| sqlite | §sqlite://./data.sqlite§ |
| clickhouse | §clickhouse://user:pass@localhost:9000/dbname§ |
| scylla | §scylla://host:9042/keyspace§ |

---

## 8. Writing schema (§@@SCHEMADIR@@/§)

Plain DDL. Scaffolded schema for §@@PROVIDER@@§:

§§§sql
@@SCHEMA@@
§§§

Workflow: edit DDL → §flash migrate "<msg>"§ → §flash apply§ → §flash gen§.

Flash auto-detects column/table renames and preserves data.

---

## 9. Writing queries

Each query starts with exactly:

§§§sql
-- name: <QueryName> <:cmd>
§§§

§<QueryName>§ becomes the generated function name.
§<:cmd>§ controls the return type:

| §:cmd§ | Returns | Use for |
|---|---|---|
| §:one§ | one row (error if absent) | single-row SELECT, INSERT … RETURNING |
| §:many§ | slice of rows | multi-row SELECT |
| §:exec§ | nothing | INSERT/UPDATE/DELETE without return |
| §:execresult§ | rows-affected / last-insert-id | MySQL inserts |

**Parameters use §@@PARAM@@§ placeholders for §@@PROVIDER@@§.**
Postgres uses §$1, $2, …§; MySQL/SQLite/ClickHouse/Scylla use §?§.

Scaffolded queries:

§§§sql
@@QUERIES@@
§§§

Rules:
- Prefer §RETURNING§ (Postgres/SQLite) so inserts can be §:one§.
- MySQL has no §RETURNING§ — use §:execresult§ for inserts.
- Any §@@EXT@@§ file under §db/queries/§ works; filenames are free.

---

## 10. Supported databases

| Database | ORM | Migrations | Studio | Parameter style |
|---|---|---|---|---|
| **PostgreSQL** | ✅ Full | ✅ | ✅ SQL Studio | §$1, $2, …§ |
| **MySQL** | ✅ Full | ✅ | ✅ SQL Studio | §?§ |
| **SQLite** | ✅ Full | ✅ | ✅ SQL Studio | §?§ |
| **ScyllaDB / Cassandra** | ✅ Beta | ✅ | ✅ SQL Studio | §?§ (CQL) |
| **ClickHouse** | ✅ Beta | ✅ | ✅ SQL Studio | §?§ |
| **MongoDB** | ❌ ORM | ❌ | ✅ Visual Management | N/A |
| **Redis** | ❌ ORM | ❌ | ✅ Visual Management | N/A |

This project uses **§@@PROVIDER@@§** — parameters are written as §@@PARAM@@§.

---

## 11. Annotations

Placed as §--§ comment lines directly before or after §-- name:§.

### §-- @required: col1, col2§ (or §*§)
Marks columns as non-nullable in generated types even when the schema allows
NULL. Mainly for ScyllaDB (all non-PK columns are nullable by default in CQL).
§-- @required: *§ marks every column.

§§§sql
-- name: GetUser :one
-- @required: name, email
SELECT id, name, email FROM users WHERE id = @@PARAM@@;
§§§

### §-- @json <field> { ... }§ or §-- @json import <file>.json as <field>§
Declares a typed structure for a JSON/JSONB column so the generator emits a
typed class/struct instead of a raw string. (See §12§ for full examples.)

### §-- @cache { ... }§
Caches a read query in Redis. (See §13§ for full examples.)

---

## 12. Typed JSON columns

FlashORM can generate typed structs/classes for JSONB columns instead of raw
strings. Supported types: §string§, §int§, §float§, §boolean§, §string[]§,
§int[]§, §float[]§, §boolean[]§, §any§.

### Inline definition

§§§sql
-- name: GetUser :one
-- @json settings {"theme": "string", "language": "string", "font_size": "int", "dark_mode": "boolean"}
-- @json metadata {"level": "int", "badges": "string[]", "xp": "int"}
SELECT id, name, email, settings, metadata FROM users WHERE id = @@PARAM@@;
§§§

### Import from a JSON file

§§§sql
-- name: GetUser :one
-- @json import user_settings.json as settings
SELECT id, name, email, settings FROM users WHERE id = @@PARAM@@;
§§§

§§§json
// db/json/user_settings.json
{"theme": "string", "language": "string", "font_size": "int", "notifications": "boolean"}
§§§

Enable the JSON path in §flash.toml§:

§§§toml
json_path = "db/json"
§§§

### What gets generated

All fields are nullable. Unspecified fields are accessible via §.raw§ / §.get("key")§.

§§§go
// Go — typed, no manual JSON parsing:
user, _ := q.GetUser(42)
theme  := user.Settings.Theme              // *string
level  := user.Metadata.Level             // *int
extra  := user.Settings.Get("custom_key") // untyped fallback
§§§

§§§kotlin
// Kotlin
val user = queries.getUser(42)
val theme  = user?.settings?.theme           // String?
val level  = user?.metadata?.level           // Int?
val extra  = user?.settings?.get("custom")   // any unspecified field
§§§

§§§typescript
// TypeScript
const user = await queries.getUser(42)
const theme = user?.settings?.theme          // string | null
const extra = user?.settings?.get("custom")  // unknown
§§§

§§§python
# Python
user = await queries.get_user(42)
theme = user.settings.theme if user else None   # str | None
§§§

§§§rust
// Rust
let user = queries.get_user(42).await?;
let theme = user.settings.as_ref().and_then(|s| s.theme.as_ref());
§§§

---

## 13. Query caching (Redis)

Enable in §flash.toml§:

§§§toml
[cache]
enabled       = true
redis_url_env = "REDIS_URL"
default_ttl   = "5m"
prefix        = "flash"
§§§

Add §REDIS_URL§ to §.env§:

§§§
REDIS_URL=redis://localhost:6379
# or with auth:
REDIS_URL=redis://:password@redis-host:6379/0
§§§

### Annotating a query

§§§sql
-- name: GetUser :one
-- @cache {"ttl": "60s", "name": "UserCache", "tags": ["users"], "dep": ["UpdateUser", "DeleteUser"]}
SELECT id, name, email FROM users WHERE id = @@PARAM@@;

-- name: ListPublishedPosts :many
-- @cache {"ttl": "15s", "name": "PublishedPostsCache", "tags": ["posts"], "dep": ["CreatePost", "PublishPost", "DeletePost"]}
SELECT id, title, created_at FROM posts WHERE status = 'published' ORDER BY created_at DESC LIMIT @@PARAM@@;
§§§

§@cache§ fields:

| Field | Meaning | Default |
|---|---|---|
| §ttl§ | Time-to-live: §30s§, §5m§, §1h§, §24h§, §7d§ | §default_ttl§ from config |
| §name§ | Cache accessor name | §<QueryName>Cache§ |
| §tags§ | Labels for bulk purge | none |
| §dep§ | Mutation query names that auto-invalidate this cache | none |

### Generated code — cache-first query wrapper

§§§go
// Go — cache-first: hits Redis, falls back to DB, stores result
user, err := q.GetUserCached(42)

// Auto-purge wrapper: runs UPDATE then purges UserCache:{id}
err = q.UpdateUserAndPurge(arg)
§§§

§§§typescript
// TypeScript
const user = await getUserCached(queries, 42);
await updateUserAndPurge(queries, name, email, bio, id);
§§§

§§§python
# Python
user = await get_user_cached(queries, 42)
await update_user_and_purge(queries, name, email, bio, id)
§§§

§§§rust
// Rust
let user = queries.get_user_cached(42).await?;
queries.update_user_and_purge(params).await?;
§§§

§§§kotlin
// Kotlin
val user = cachedQueries.getUserCached(42, User::class.java)
cachedQueries.updateUserAndPurge(name, email, bio, id)
§§§

### Manual cache control via named accessors

Each §@cache§ annotation also generates a named accessor:

§§§go
// Go
flash_gen.UserCache.Get(42)         // read from cache
flash_gen.UserCache.Set(42, user)   // write manually
flash_gen.UserCache.Del(42)         // delete one entry
flash_gen.UserCache.Purge()         // purge all UserCache:* entries
§§§

### Typed tag purging — bulk invalidation

Flash generates typed constants from your tag strings so you cannot misspell them:

§§§go
// Go — TagUsers, TagPosts, etc. are generated from your @cache "tags"
flash_gen.Cache.PurgeTag(flash_gen.TagUsers)   // purges UserCache, UserProfileCache, etc.
flash_gen.Cache.PurgeTag(flash_gen.TagPosts)
§§§

§§§rust
// Rust
CacheTag::Users.purge();
CacheTag::Posts.purge();
§§§

§§§typescript
// TypeScript
await purgeTag(CacheTag.Users);
await purgeTag(CacheTag.Posts);
§§§

§§§python
# Python
purge_tag(CacheTag.USERS)
§§§

§§§kotlin
// Kotlin
CacheTag.USERS.purge()
§§§

§§§java
// Java
CacheTag.USERS.purge();
§§§

---

## 14. Code generation & drivers

§flash gen§ auto-detects project type (§package.json§ → JS, §pyproject.toml§ →
Python, §Cargo.toml§ → Rust, Gradle/Maven → Kotlin/Java, else Go) and writes to
enabled §[gen.*]§ targets. Force a full rebuild with §flash gen -f§.

After generation Flash prints §Output: <dir>/§ — use this to confirm the
actual §out§ path.

Drivers for §@@PROVIDER@@§:

§§§
@@DRIVERS@@
§§§

Set with §driver = "<name>"§ inside the §[gen.*]§ block.

### Generator selected by §flash init§

This project was initialized for **@@LANGUAGE@@**. The enabled block in
§flash.toml§ is the source of truth; do not use examples for another language
unless you explicitly enable that additional §[gen.*]§ target.

@@LANGGUIDE@@

### Rust validation modes

Rust generation supports two §sqlx§ modes. Choose one in §flash.toml§:

§§§toml
[gen.rust]
enabled = true
out = "src/flash_gen"
driver = "sqlx"
macros = false  # runtime-checked; this is the default
§§§

With §macros = false§, Flash emits §sqlx::query§, §sqlx::query_as§, and
§sqlx::query_scalar§ plus §.bind(...)§ calls. Generation and compilation do
not need a live database. SQL syntax, parameter types, and result decoding are
checked when the generated async method executes:

§§§bash
flash gen
cargo build
DATABASE_URL="postgres://..." cargo run
§§§

The generated methods still return §Result<T, sqlx::Error>§, so handle runtime
database errors with §?§, §match§, or your application's error type.

Set §macros = true§ to emit §sqlx::query!§, §sqlx::query_as!§, and
§sqlx::query_scalar!§ instead. These validate SQL against the database at
**compile time**. §DATABASE_URL§ must point to a running database whose schema
matches the Flash schema whenever §cargo check§ or §cargo build§ compiles the
generated code:

§§§toml
[gen.rust]
enabled = true
out = "src/flash_gen"
driver = "sqlx"
macros = true
§§§

§§§bash
flash migrate "sync schema"
flash apply
flash gen -f
DATABASE_URL="postgres://..." cargo check
§§§

---

## 15. FlashORM Studio

§flash studio§ launches a local visual editor:

§§§bash
flash studio                                      # uses DATABASE_URL
flash studio "postgres://user:pass@host:5432/db"  # explicit URL
flash studio "mongodb://localhost:27017/mydb"      # MongoDB
flash studio "redis://localhost:6379"              # Redis
§§§

---

## 16. Filing bugs — §flash issues§

If you hit unexpected behavior or a generation bug:

§§§bash
flash issues \
  -k bug \
  -t "gen: <short specific summary>" \
  -b "<what you were doing and what happened>" \
  --repro "1. ...  2. ...  3. ..." \
  --expected "<expected>" \
  --actual "<actual, including exact error text>"
§§§

Flags: §-k§ kind (§bug§/§feature§/§question§/§docs§), §--print§ preview without
submitting, §-y§ skip confirm. Version, OS, and provider are attached
automatically.

---

## 17. Golden rules for an agent

1. **Read §flash.toml§ first** — especially §[gen.*].out§ — to know where
   generated files actually live. Never assume §flash_gen/§.
2. **Edit §@@EXT@@§ files, never generated files.** They are overwritten on §flash gen§.
3. **Re-run §flash gen§** after any schema or query change.
4. **Use §@@PARAM@@§ placeholders** for this provider (§@@PROVIDER@@§).
5. **Pick the right §:cmd§** — §:one§/§:many§ for reads, §:exec§/§:execresult§ for writes.
6. **Secrets go in §.env§** via §url_env§; never hard-code connection strings.
7. **Migrations:** §flash migrate "<msg>"§ then §flash apply§. Never hand-edit applied migrations.
8. **JSON columns:** use §-- @json§ to get typed structs instead of raw strings.
9. **Caching is opt-in:** enable §[cache]§, annotate reads with §-- @cache§, wire §dep§.
10. **Rust macros need a live DB at compile time** when §macros = true§.
11. **Broken generation? Run §flash issues§** with real reproduction steps.
`

// agentLanguageGuide returns the language selected by init and a minimal,
// copy/paste usage example that matches that generator's API.
func (pt *ProjectTemplate) agentLanguageGuide() (string, string) {
	switch {
	case pt.IsRustProject:
		return "Rust", "" + "§§§toml\n# Cargo.toml\nsqlx = { version = \"0.9\", features = [\"runtime-tokio\", \"postgres\", \"macros\"] }\n§§§\n\nGenerated files are Rust modules under §[gen.rust].out§. Include the module\nwith `mod flash_gen;`, create a `sqlx::PgPool`, then call async methods on\n`flash_gen::db::Queries`; results are `Result<T, sqlx::Error>` and nullable SQL\ncolumns are `Option<T>`.\n\n§§§rust\nmod flash_gen;\nuse flash_gen::db::Queries;\nlet pool = sqlx::PgPool::connect(&std::env::var(\"DATABASE_URL\")?).await?;\nlet queries = Queries::new(pool);\nlet user = queries.get_user(1).await?;\nlet users = queries.list_users(20, 0).await?;\n§§§\n\nSet `macros = true` only when a live database is available at compile time;\nFlash then emits `sqlx::query!` macros for schema validation."
	case pt.IsPythonProject:
		return "Python", "" + "§§§toml\n[gen.python]\nenabled = true\nasync = true\n§§§\n\nGenerated modules are importable from §[gen.python].out§. Async mode uses\n`asyncio` and the configured driver (normally `asyncpg` for PostgreSQL); set\n`async = false` for synchronous code. Pass an asyncpg/psycopg/SQLite connection\nor pool to `newq`; Flash does not create the connection for you.\n\n§§§python\nfrom flash_gen.database import newq\nqueries = newq(db_connection)\nuser = await queries.get_user(1)\nusers = await queries.list_users(20, 0)\n§§§"
	case pt.IsKotlinProject:
		return "Kotlin", "" + "§§§kotlin\n// Generated package is the value of [gen.kotlin].package\nval queries = Queries.newq(connection)\nval user = queries.getUser(1)\nval users = queries.listUsers(20, 0)\n§§§\n\nKotlin generation targets JDBC by default; set `driver = \"exposed\"` or\n`driver = \"r2dbc\"` when your project uses those runtimes."
	case pt.IsJavaProject:
		return "Java", "" + "§§§java\n// Generated package is the value of [gen.java].package\nQueries queries = Queries.newq(connection);\nUsers user = queries.getUser(1);\njava.util.List<Users> users = queries.listUsers(20, 0);\n§§§\n\nJava generation targets JDBC by default; `jooq` and `hibernate` are available\nthrough the `driver` setting."
	case pt.IsNodeProject:
		return "JavaScript/TypeScript", "" + "§§§typescript\nimport { Newq } from './flash_gen';\nconst queries = Newq(db); // db is a pg/mysql2/bun:sqlite client\nconst user = await queries.getUser(1);\nconst users = await queries.listUsers(20, 0);\n§§§\n\nThe JS generator emits JavaScript plus `.d.ts` declarations. Set `driver` in\n§[gen.js]§ to `pg`, `postgres`, `mysql2`, or the provider's supported driver."
	default:
		return "Go", "" + "§§§go\nimport \"your/module/flash_gen\"\nqueries := flash_gen.Newq(db)\nuser, err := queries.GetUser(1)\nusers, err := queries.ListUsers(20, 0)\n§§§\n\nGo generation uses `database/sql` by default; set `driver = \"pgx\"` for the\npgx-native path. pgx and Scylla methods also accept `context.Context`."
	}
}
