// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.time.LocalDateTime;

public record AuditLog(
    int id,
    String table_name,
    String record_id,
    String action,
    java.util.Map<String, Object> old_data,
    java.util.Map<String, Object> new_data,
    Integer changed_by,
    LocalDateTime changed_at
) {}
