// Code generated by FlashORM. DO NOT EDIT.

package java;


public record CreateUserFullArgs(
    String name,
    String email,
    int age,
    String bio,
    java.util.Map<String, Object> preferences,
    java.util.List<String> tags,
    UserRole role
) {}
