// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.time.LocalDateTime;

public record CreateSubscriptionArgs(
    int user_id,
    SubscriptionTier tier,
    LocalDateTime expires_at,
    boolean auto_renew
) {}
