// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.time.LocalDateTime;

public record GetAuditLogForTableRow(
    int id,
    String table_name,
    String record_id,
    String action,
    Integer changed_by,
    LocalDateTime changed_at
) {}
