// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.time.LocalDateTime;

public record GetAllContentByUserRow(
    String content_type,
    String content_id,
    String content_summary,
    LocalDateTime created_at
) {}
