// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.util.UUID;
import java.time.LocalDateTime;

public record GetMediaByTypeRow(
    UUID id,
    int user_id,
    String url,
    long size_bytes,
    String mime_type,
    LocalDateTime created_at
) {}
