// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.util.UUID;
import java.time.LocalDateTime;

public record GetOrdersByUserRow(
    UUID id,
    double total_amount,
    String discount_pct,
    OrderState state,
    String shipping_addr,
    LocalDateTime placed_at
) {}
