// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.time.LocalDateTime;

public record GetPostsWithCommentCountRow(
    int id,
    String title,
    LocalDateTime created_at,
    int comment_count,
    int unique_commenters,
    LocalDateTime last_comment_at
) {}
