// Code generated by FlashORM. DO NOT EDIT.

package java;


public record GetPostWithCommentsRow(
    int post_id,
    String title,
    String content,
    String author,
    String comment_text,
    String commenter
) {}
