// Code generated by FlashORM. DO NOT EDIT.

package java;


public record GetStorageUsedByUserRow(
    Double total_bytes,
    int total_files,
    int image_count,
    int video_count,
    int document_count
) {}
