// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.util.UUID;

public record GetTopTagsRow(
    UUID id,
    String name,
    String slug,
    String color,
    long post_count
) {}
