// Code generated by FlashORM. DO NOT EDIT.

package java;


public record GetUserPostRankingsRow(
    int id,
    String name,
    long post_count,
    long post_rank,
    long dense_post_rank,
    long row_num
) {}
