// Code generated by FlashORM. DO NOT EDIT.

package java;


public record GetUserWithStatsRow(
    int published_posts,
    int total_comments,
    int unread_notifications,
    Double storage_used
) {}
