// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.time.LocalDateTime;

public record GetUserAgeStatsRow(
    LocalDateTime first_joined,
    LocalDateTime last_joined,
    long total,
    Double avg_age,
    Double avg_name_length
) {}
