// Code generated by FlashORM. DO NOT EDIT.

package java;


public record GetUserPostRankingsRow(
    int id,
    String name,
    long post_count,
    int post_rank,
    int dense_post_rank,
    int row_num
) {}
