// Code generated by FlashORM. DO NOT EDIT.

package java;


public record GetUserDisplayInfoRow(
    int id,
    String name,
    String email,
    String display_address,
    String age,
    String bio
) {}
