// Code generated by FlashORM. DO NOT EDIT.

package java;


public record GetUserShippingAddressRow(
    int id,
    String name,
    String shipping,
    String shipping_city,
    String shipping_country
) {}
