// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.util.UUID;
import java.time.LocalDateTime;

public enum PostStatus {
    DRAFT,
    PUBLISHED,
    ARCHIVED;
}

public enum UserRole {
    ADMIN,
    MODERATOR,
    USER,
    GUEST;
}

public enum SubscriptionTier {
    FREE,
    PRO,
    ENTERPRISE;
}

public enum OrderState {
    PENDING,
    CONFIRMED,
    SHIPPED,
    DELIVERED,
    CANCELLED,
    REFUNDED;
}

public record Users(
    int id,
    String name,
    String address,
    boolean isadmin,
    Integer age,
    Integer age_range,
    String bio,
    String email,
    java.util.Map<String, Object> preferences,
    java.util.List<String> tags,
    UUID avatar_hash,
    String shipping,
    LocalDateTime created_at,
    LocalDateTime updated_at,
    UserRole role
) {}

public record Categories(
    int id,
    String name,
    String slug,
    String color,
    java.util.Map<String, Object> metadata,
    LocalDateTime created_at
) {}

public record Posts(
    int id,
    int user_id,
    int category_id,
    String title,
    String content,
    String excerpt,
    java.util.List<String> tags,
    java.util.Map<String, Object> metadata,
    long view_count,
    boolean is_featured,
    LocalDateTime published_at,
    LocalDateTime created_at,
    LocalDateTime updated_at,
    PostStatus status
) {}

public record Comments(
    int id,
    int post_id,
    int user_id,
    Integer parent_id,
    String content,
    LocalDateTime created_at
) {}

public record Subscriptions(
    int id,
    int user_id,
    SubscriptionTier tier,
    LocalDateTime started_at,
    LocalDateTime expires_at,
    boolean auto_renew
) {}

public record Orders(
    UUID id,
    int user_id,
    double total_amount,
    String discount_pct,
    String shipping_addr,
    java.util.Map<String, Object> line_items,
    OrderState state,
    LocalDateTime placed_at,
    LocalDateTime updated_at
) {}

public record AuditLog(
    int id,
    String table_name,
    String record_id,
    String action,
    java.util.Map<String, Object> old_data,
    java.util.Map<String, Object> new_data,
    Integer changed_by,
    LocalDateTime changed_at
) {}

public record UserSessions(
    UUID id,
    int user_id,
    String token,
    String ip_address,
    String user_agent,
    LocalDateTime expires_at,
    LocalDateTime created_at
) {}

public record Notifications(
    int id,
    int user_id,
    String type,
    String title,
    String body,
    boolean is_read,
    java.util.Map<String, Object> metadata,
    LocalDateTime created_at
) {}

public record Tags(
    int id,
    String name,
    String slug,
    String color
) {}

public record PostTags(
    int post_id,
    int tag_id
) {}

public record Media(
    UUID id,
    int user_id,
    Integer post_id,
    String type,
    String url,
    long size_bytes,
    String mime_type,
    Integer width,
    Integer height,
    java.util.Map<String, Object> metadata,
    LocalDateTime created_at
) {}

public record ActiveUsers(
    String id,
    String name,
    String email,
    String role,
    String created_at
) {}

public record UserActivitySummary(
    String id,
    String name,
    String email,
    String post_count,
    String comment_count,
    String last_post_at,
    String user_type
) {}

public record PostStats(
    String post_id,
    String title,
    String comment_count,
    String unique_commenters,
    String last_comment_at
) {}

