// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.util.UUID;
import java.time.LocalDateTime;

public record Orders(
    UUID id,
    int user_id,
    double total_amount,
    String discount_pct,
    String shipping_addr,
    java.util.Map<String, Object> line_items,
    OrderState state,
    LocalDateTime placed_at,
    LocalDateTime updated_at
) {}
