// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.time.LocalDateTime;

public record Posts(
    int id,
    int user_id,
    int category_id,
    String title,
    String content,
    String excerpt,
    java.util.List<String> tags,
    java.util.Map<String, Object> metadata,
    long view_count,
    boolean is_featured,
    LocalDateTime published_at,
    LocalDateTime created_at,
    LocalDateTime updated_at,
    PostStatus status
) {}
