// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.sql.Connection;

/**
 * Unified query interface. Use {@code DB.newq(conn)} to obtain an instance.
 */
public class Queries {
    private final UsersQueries users;

    Queries(Connection conn) {
        this.users = new UsersQueries(conn);
    }

    public static Queries newq(Connection conn) {
        return new Queries(conn);
    }

    public Users createUser(String name, String email) throws java.sql.SQLException {
        return this.users.createUser(name, email);
    }

    public record CreateUserFullArgs(
        String name,
        String email,
        int age,
        String bio,
        java.util.Map<String, Object> preferences,
        java.util.List<String> tags,
        UserRole role
    ) {}

    public Users createUserFull(CreateUserFullArgs args) throws java.sql.SQLException {
        return this.users.createUserFull(args);
    }

    public Users getUser(int id) throws java.sql.SQLException {
        return this.users.getUser(id);
    }

    public Users getUserByEmail(String email) throws java.sql.SQLException {
        return this.users.getUserByEmail(email);
    }

    public Users updateUserName(String name, int id) throws java.sql.SQLException {
        return this.users.updateUserName(name, id);
    }

    public void updateUserRole(UserRole role, int id) throws java.sql.SQLException {
        this.users.updateUserRole(role, id);
    }

    public void deleteUser(int id) throws java.sql.SQLException {
        this.users.deleteUser(id);
    }

    public java.util.List<Users> listUsers(int limit, int offset) throws java.sql.SQLException {
        return this.users.listUsers(limit, offset);
    }

    public record UpsertUserArgs(
        String name,
        String email,
        UserRole role
    ) {}

    public Users upsertUser(UpsertUserArgs args) throws java.sql.SQLException {
        return this.users.upsertUser(args);
    }

    public record UpsertUserWithCOALESCEArgs(
        String name,
        String email,
        String bio
    ) {}

    public Users upsertUserWithCOALESCE(UpsertUserWithCOALESCEArgs args) throws java.sql.SQLException {
        return this.users.upsertUserWithCOALESCE(args);
    }

    public java.util.List<GetUsersWithNullAddressRow> getUsersWithNullAddress() throws java.sql.SQLException {
        return this.users.getUsersWithNullAddress();
    }

    public java.util.List<GetUsersWithBioRow> getUsersWithBio() throws java.sql.SQLException {
        return this.users.getUsersWithBio();
    }

    public GetUserDisplayInfoRow getUserDisplayInfo(int id) throws java.sql.SQLException {
        return this.users.getUserDisplayInfo(id);
    }

    public record SearchUsersWithCOALESCEArgs(
        String name,
        String email,
        int age,
        int limit,
        int offset
    ) {}

    public java.util.List<SearchUsersWithCOALESCERow> searchUsersWithCOALESCE(SearchUsersWithCOALESCEArgs args) throws java.sql.SQLException {
        return this.users.searchUsersWithCOALESCE(args);
    }

    public java.util.List<GetUsersCreatedBetweenRow> getUsersCreatedBetween(LocalDateTime created_at, LocalDateTime created_at2) throws java.sql.SQLException {
        return this.users.getUsersCreatedBetween(created_at, created_at2);
    }

    public java.util.List<GetUsersByAgeRangeRow> getUsersByAgeRange(int age, int age2) throws java.sql.SQLException {
        return this.users.getUsersByAgeRange(age, age2);
    }

    public java.util.List<GetUsersByGeneratedRangeRow> getUsersByGeneratedRange(int age_range) throws java.sql.SQLException {
        return this.users.getUsersByGeneratedRange(age_range);
    }

    public record GetRecentUsersArgs(
        LocalDateTime created_at,
        int limit,
        int offset
    ) {}

    public java.util.List<Users> getRecentUsers(GetRecentUsersArgs args) throws java.sql.SQLException {
        return this.users.getRecentUsers(args);
    }

    public GetUserPreferencesRow getUserPreferences(int id) throws java.sql.SQLException {
        return this.users.getUserPreferences(id);
    }

    public void updateUserPreferences(java.util.Map<String, Object> preferences, int id) throws java.sql.SQLException {
        this.users.updateUserPreferences(preferences, id);
    }

    public java.util.List<FindUsersByJsonKeyRow> findUsersByJsonKey(java.util.Map<String, Object> preferences) throws java.sql.SQLException {
        return this.users.findUsersByJsonKey(preferences);
    }

    public java.util.List<FindUsersByJsonContainsRow> findUsersByJsonContains(java.util.Map<String, Object> preferences) throws java.sql.SQLException {
        return this.users.findUsersByJsonContains(preferences);
    }

    public java.util.List<GetUsersWithTagRow> getUsersWithTag(java.util.List<String> tags) throws java.sql.SQLException {
        return this.users.getUsersWithTag(tags);
    }

    public java.util.List<GetUsersWithAnyTagRow> getUsersWithAnyTag(java.util.List<String> tags) throws java.sql.SQLException {
        return this.users.getUsersWithAnyTag(tags);
    }

    public void addUserTag(java.util.List<String> tags, int id) throws java.sql.SQLException {
        this.users.addUserTag(tags, id);
    }

    public void removeUserTag(java.util.List<String> tags, int id) throws java.sql.SQLException {
        this.users.removeUserTag(tags, id);
    }

    public GetUserShippingAddressRow getUserShippingAddress(int id) throws java.sql.SQLException {
        return this.users.getUserShippingAddress(id);
    }

    public record UpdateUserShippingArgs(
        String shipping_field1,
        String shipping_field2,
        String shipping_field3,
        String shipping_field4,
        String shipping_field5,
        int id
    ) {}

    public void updateUserShipping(UpdateUserShippingArgs args) throws java.sql.SQLException {
        this.users.updateUserShipping(args);
    }

    public record GetComplexUserAnalyticsArgs(
        String total_posts,
        String total_comments,
        String limit
    ) {}

    public java.util.List<GetComplexUserAnalyticsRow> getComplexUserAnalytics(GetComplexUserAnalyticsArgs args) throws java.sql.SQLException {
        return this.users.getComplexUserAnalytics(args);
    }

    public java.util.List<GetPostWithActiveCommentersRow> getPostWithActiveCommenters(String rn, String post_id) throws java.sql.SQLException {
        return this.users.getPostWithActiveCommenters(rn, post_id);
    }

    public java.util.List<GetUserPostRankingsRow> getUserPostRankings(int limit) throws java.sql.SQLException {
        return this.users.getUserPostRankings(limit);
    }

    public java.util.List<GetUserTrendingPostsRow> getUserTrendingPosts(int user_id, int limit) throws java.sql.SQLException {
        return this.users.getUserTrendingPosts(user_id, limit);
    }

    public GetPostCountByUserRow getPostCountByUser(String user_id) throws java.sql.SQLException {
        return this.users.getPostCountByUser(user_id);
    }

    public java.util.List<GetUsersWithManyPostsRow> getUsersWithManyPosts(int min_count) throws java.sql.SQLException {
        return this.users.getUsersWithManyPosts(min_count);
    }

    public java.util.List<GetPostsWithCommentCountRow> getPostsWithCommentCount(int limit, int offset) throws java.sql.SQLException {
        return this.users.getPostsWithCommentCount(limit, offset);
    }

    public java.util.List<GetUsersWithActivityLevelRow> getUsersWithActivityLevel() throws java.sql.SQLException {
        return this.users.getUsersWithActivityLevel();
    }

    public java.util.List<GetPostWithCommentsRow> getPostWithComments(int id) throws java.sql.SQLException {
        return this.users.getPostWithComments(id);
    }

    public GetPostDetailsWithAllRelationsRow getPostDetailsWithAllRelations(int id) throws java.sql.SQLException {
        return this.users.getPostDetailsWithAllRelations(id);
    }

    public Integer countUsersByRole(UserRole role) throws java.sql.SQLException {
        return this.users.countUsersByRole(role);
    }

    public CountUsersRow countUsers() throws java.sql.SQLException {
        return this.users.countUsers();
    }

    public java.util.List<GetUserRoleCountRow> getUserRoleCount() throws java.sql.SQLException {
        return this.users.getUserRoleCount();
    }

    public GetUserAgeStatsRow getUserAgeStats() throws java.sql.SQLException {
        return this.users.getUserAgeStats();
    }

    public java.util.List<GetPostsGroupedByStatusRow> getPostsGroupedByStatus(int count_threshold) throws java.sql.SQLException {
        return this.users.getPostsGroupedByStatus(count_threshold);
    }

    public java.util.List<GetDistinctCommentersRow> getDistinctCommenters() throws java.sql.SQLException {
        return this.users.getDistinctCommenters();
    }

    public java.util.List<GetLatestPostPerUserRow> getLatestPostPerUser() throws java.sql.SQLException {
        return this.users.getLatestPostPerUser();
    }

    public record SearchUsersArgs(
        String name,
        String email,
        int limit,
        int offset
    ) {}

    public java.util.List<SearchUsersRow> searchUsers(SearchUsersArgs args) throws java.sql.SQLException {
        return this.users.searchUsers(args);
    }

    public record SearchPostsByTitleArgs(
        String title,
        int limit,
        int offset
    ) {}

    public java.util.List<SearchPostsByTitleRow> searchPostsByTitle(SearchPostsByTitleArgs args) throws java.sql.SQLException {
        return this.users.searchPostsByTitle(args);
    }

    public java.util.List<FullTextSearchPostsRow> fullTextSearchPosts(String search_query, int limit) throws java.sql.SQLException {
        return this.users.fullTextSearchPosts(search_query, limit);
    }

    public java.util.List<GetUserRegistrationStatsRow> getUserRegistrationStats() throws java.sql.SQLException {
        return this.users.getUserRegistrationStats();
    }

    public java.util.List<GetWeeklyPostStatsRow> getWeeklyPostStats(LocalDateTime created_at) throws java.sql.SQLException {
        return this.users.getWeeklyPostStats(created_at);
    }

    public java.util.List<Users> getUsersInIds(int id) throws java.sql.SQLException {
        return this.users.getUsersInIds(id);
    }

    public java.util.List<GetUsersByNamesRow> getUsersByNames(String name) throws java.sql.SQLException {
        return this.users.getUsersByNames(name);
    }

    public java.util.List<GetUsersWhoCommentedRow> getUsersWhoCommented() throws java.sql.SQLException {
        return this.users.getUsersWhoCommented();
    }

    public java.util.List<GetUsersWithNoPostsRow> getUsersWithNoPosts() throws java.sql.SQLException {
        return this.users.getUsersWithNoPosts();
    }

    public java.util.List<GetAllContentByUserRow> getAllContentByUser(int user_id, int limit) throws java.sql.SQLException {
        return this.users.getAllContentByUser(user_id, limit);
    }

    public java.util.List<ActiveUsers> getActiveUsers(int limit) throws java.sql.SQLException {
        return this.users.getActiveUsers(limit);
    }

    public java.util.List<UserActivitySummary> getUserActivitySummary(String post_count, String comment_count) throws java.sql.SQLException {
        return this.users.getUserActivitySummary(post_count, comment_count);
    }

    public void refreshPostStats() throws java.sql.SQLException {
        this.users.refreshPostStats();
    }

    public java.util.List<PostStats> getPostStats(int limit) throws java.sql.SQLException {
        return this.users.getPostStats(limit);
    }

    public java.util.List<GetUserSubscriptionsRow> getUserSubscriptions(int user_id) throws java.sql.SQLException {
        return this.users.getUserSubscriptions(user_id);
    }

    public record CreateSubscriptionArgs(
        int user_id,
        SubscriptionTier tier,
        LocalDateTime expires_at,
        boolean auto_renew
    ) {}

    public Subscriptions createSubscription(CreateSubscriptionArgs args) throws java.sql.SQLException {
        return this.users.createSubscription(args);
    }

    public java.util.List<GetOrdersByUserRow> getOrdersByUser(int user_id, int limit) throws java.sql.SQLException {
        return this.users.getOrdersByUser(user_id, limit);
    }

    public java.util.List<GetOrdersInStateRow> getOrdersInState(OrderState state, int limit) throws java.sql.SQLException {
        return this.users.getOrdersInState(state, limit);
    }

    public record GetAuditLogForUserArgs(
        int changed_by,
        int limit,
        int offset
    ) {}

    public java.util.List<GetAuditLogForUserRow> getAuditLogForUser(GetAuditLogForUserArgs args) throws java.sql.SQLException {
        return this.users.getAuditLogForUser(args);
    }

    public java.util.List<GetAuditLogForTableRow> getAuditLogForTable(String table_name, int limit) throws java.sql.SQLException {
        return this.users.getAuditLogForTable(table_name, limit);
    }

    public GetDashboardStatsRow getDashboardStats() throws java.sql.SQLException {
        return this.users.getDashboardStats();
    }

    public java.util.List<GetTopCommentersRow> getTopCommenters(int limit) throws java.sql.SQLException {
        return this.users.getTopCommenters(limit);
    }

    public java.util.List<GetEngagementTimeSeriesRow> getEngagementTimeSeries(LocalDateTime created_at) throws java.sql.SQLException {
        return this.users.getEngagementTimeSeries(created_at);
    }

    public Categories createCategory(String name) throws java.sql.SQLException {
        return this.users.createCategory(name);
    }

    public record CreatePostArgs(
        int user_id,
        int category_id,
        String title,
        String content
    ) {}

    public Posts createPost(CreatePostArgs args) throws java.sql.SQLException {
        return this.users.createPost(args);
    }

    public record CreateCommentArgs(
        int post_id,
        int user_id,
        String content
    ) {}

    public Comments createComment(CreateCommentArgs args) throws java.sql.SQLException {
        return this.users.createComment(args);
    }

    public void deleteOldUsers(LocalDateTime created_at) throws java.sql.SQLException {
        this.users.deleteOldUsers(created_at);
    }

    public void updateUserTimestamp(LocalDateTime updated_at, int id) throws java.sql.SQLException {
        this.users.updateUserTimestamp(updated_at, id);
    }

    public record CreateNotificationArgs(
        int user_id,
        String type,
        String title,
        String body,
        java.util.Map<String, Object> metadata
    ) {}

    public Notifications createNotification(CreateNotificationArgs args) throws java.sql.SQLException {
        return this.users.createNotification(args);
    }

    public record GetNotificationsByUserArgs(
        int user_id,
        int limit,
        int offset
    ) {}

    public java.util.List<Notifications> getNotificationsByUser(GetNotificationsByUserArgs args) throws java.sql.SQLException {
        return this.users.getNotificationsByUser(args);
    }

    public Integer getUnreadCount(int user_id) throws java.sql.SQLException {
        return this.users.getUnreadCount(user_id);
    }

    public void markNotificationRead(int id, int user_id) throws java.sql.SQLException {
        this.users.markNotificationRead(id, user_id);
    }

    public void markAllNotificationsRead(int user_id) throws java.sql.SQLException {
        this.users.markAllNotificationsRead(user_id);
    }

    public void deleteOldNotifications(int user_id, LocalDateTime created_at) throws java.sql.SQLException {
        this.users.deleteOldNotifications(user_id, created_at);
    }

    public record GetNotificationsByTypeArgs(
        int user_id,
        String type,
        int limit
    ) {}

    public java.util.List<GetNotificationsByTypeRow> getNotificationsByType(GetNotificationsByTypeArgs args) throws java.sql.SQLException {
        return this.users.getNotificationsByType(args);
    }

    public record CreateTagArgs(
        String name,
        String slug,
        String color
    ) {}

    public Tags createTag(CreateTagArgs args) throws java.sql.SQLException {
        return this.users.createTag(args);
    }

    public Tags getTagBySlug(String slug) throws java.sql.SQLException {
        return this.users.getTagBySlug(slug);
    }

    public java.util.List<Tags> getAllTags() throws java.sql.SQLException {
        return this.users.getAllTags();
    }

    public void addTagToPost(int post_id, int tag_id) throws java.sql.SQLException {
        this.users.addTagToPost(post_id, tag_id);
    }

    public void removeTagFromPost(int post_id, int tag_id) throws java.sql.SQLException {
        this.users.removeTagFromPost(post_id, tag_id);
    }

    public java.util.List<Tags> getTagsForPost(int post_id) throws java.sql.SQLException {
        return this.users.getTagsForPost(post_id);
    }

    public record GetPostsByTagArgs(
        String slug,
        int limit,
        int offset
    ) {}

    public java.util.List<GetPostsByTagRow> getPostsByTag(GetPostsByTagArgs args) throws java.sql.SQLException {
        return this.users.getPostsByTag(args);
    }

    public java.util.List<GetTopTagsRow> getTopTags(int limit) throws java.sql.SQLException {
        return this.users.getTopTags(limit);
    }

    public record UploadMediaArgs(
        int user_id,
        int post_id,
        String type,
        String url,
        long size_bytes,
        String mime_type,
        int width,
        int height,
        java.util.Map<String, Object> metadata
    ) {}

    public Media uploadMedia(UploadMediaArgs args) throws java.sql.SQLException {
        return this.users.uploadMedia(args);
    }

    public java.util.List<GetMediaByPostRow> getMediaByPost(int post_id) throws java.sql.SQLException {
        return this.users.getMediaByPost(post_id);
    }

    public record GetMediaByUserArgs(
        int user_id,
        int limit,
        int offset
    ) {}

    public java.util.List<GetMediaByUserRow> getMediaByUser(GetMediaByUserArgs args) throws java.sql.SQLException {
        return this.users.getMediaByUser(args);
    }

    public java.util.List<GetMediaByTypeRow> getMediaByType(int user_id, String type) throws java.sql.SQLException {
        return this.users.getMediaByType(user_id, type);
    }

    public void deleteMedia(UUID id, int user_id) throws java.sql.SQLException {
        this.users.deleteMedia(id, user_id);
    }

    public GetStorageUsedByUserRow getStorageUsedByUser(int user_id) throws java.sql.SQLException {
        return this.users.getStorageUsedByUser(user_id);
    }

    public java.util.List<GetLargeMediaFilesRow> getLargeMediaFiles(long size_bytes, int limit) throws java.sql.SQLException {
        return this.users.getLargeMediaFiles(size_bytes, limit);
    }

    public record GetUserFeedArgs(
        int user_id,
        int limit,
        int offset
    ) {}

    public java.util.List<GetUserFeedRow> getUserFeed(GetUserFeedArgs args) throws java.sql.SQLException {
        return this.users.getUserFeed(args);
    }

    public java.util.List<SearchPostsFullTextRow> searchPostsFullText(String search_query, int limit) throws java.sql.SQLException {
        return this.users.searchPostsFullText(search_query, limit);
    }

    public void bulkMarkNotificationsRead(int user_id, int id) throws java.sql.SQLException {
        this.users.bulkMarkNotificationsRead(user_id, id);
    }

    public GetUserWithStatsRow getUserWithStats(int id) throws java.sql.SQLException {
        return this.users.getUserWithStats(id);
    }

    public void close() throws java.sql.SQLException {
        this.users.close();
    }
}
