// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.sql.Connection;

/**
 * Unified query interface. Use {@code DB.newq(conn)} to obtain an instance.
 */
public class Queries {
    private final UsersQueries users;

    Queries(Connection conn) {
        this.users = new UsersQueries(conn);
    }

    public static Queries newq(Connection conn) {
        return new Queries(conn);
    }

    public Users createUser(String name, String email) throws java.sql.SQLException {
        return this.users.createUser(name, email);
    }

    public Users createUserFull(String name, String email, int age, String bio, java.util.Map<String, Object> preferences, java.util.List<String> tags, UserRole role) throws java.sql.SQLException {
        return this.users.createUserFull(name, email, age, bio, preferences, tags, role);
    }

    public Users getUser(int id) throws java.sql.SQLException {
        return this.users.getUser(id);
    }

    public Users getUserByEmail(String email) throws java.sql.SQLException {
        return this.users.getUserByEmail(email);
    }

    public Users updateUserName(String name, int id) throws java.sql.SQLException {
        return this.users.updateUserName(name, id);
    }

    public void updateUserRole(UserRole role, int id) throws java.sql.SQLException {
        this.users.updateUserRole(role, id);
    }

    public void deleteUser(int id) throws java.sql.SQLException {
        this.users.deleteUser(id);
    }

    public java.util.List<Users> listUsers(int limit, int offset) throws java.sql.SQLException {
        return this.users.listUsers(limit, offset);
    }

    public Users upsertUser(String name, String email, UserRole role) throws java.sql.SQLException {
        return this.users.upsertUser(name, email, role);
    }

    public Users upsertUserWithCOALESCE(String name, String email, String bio) throws java.sql.SQLException {
        return this.users.upsertUserWithCOALESCE(name, email, bio);
    }

    public java.util.List<GetuserswithnulladdressRow> getUsersWithNullAddress() throws java.sql.SQLException {
        return this.users.getUsersWithNullAddress();
    }

    public java.util.List<GetuserswithbioRow> getUsersWithBio() throws java.sql.SQLException {
        return this.users.getUsersWithBio();
    }

    public GetuserdisplayinfoRow getUserDisplayInfo(int id) throws java.sql.SQLException {
        return this.users.getUserDisplayInfo(id);
    }

    public java.util.List<SearchuserswithcoalesceRow> searchUsersWithCOALESCE(String name, String email, int age, int limit, int offset) throws java.sql.SQLException {
        return this.users.searchUsersWithCOALESCE(name, email, age, limit, offset);
    }

    public java.util.List<GetuserscreatedbetweenRow> getUsersCreatedBetween(LocalDateTime created_at, LocalDateTime created_at2) throws java.sql.SQLException {
        return this.users.getUsersCreatedBetween(created_at, created_at2);
    }

    public java.util.List<GetusersbyagerangeRow> getUsersByAgeRange(int age, int age2) throws java.sql.SQLException {
        return this.users.getUsersByAgeRange(age, age2);
    }

    public java.util.List<GetusersbygeneratedrangeRow> getUsersByGeneratedRange(int age_range) throws java.sql.SQLException {
        return this.users.getUsersByGeneratedRange(age_range);
    }

    public java.util.List<Users> getRecentUsers(LocalDateTime created_at, int limit, int offset) throws java.sql.SQLException {
        return this.users.getRecentUsers(created_at, limit, offset);
    }

    public GetuserpreferencesRow getUserPreferences(int id) throws java.sql.SQLException {
        return this.users.getUserPreferences(id);
    }

    public void updateUserPreferences(java.util.Map<String, Object> preferences, int id) throws java.sql.SQLException {
        this.users.updateUserPreferences(preferences, id);
    }

    public java.util.List<FindusersbyjsonkeyRow> findUsersByJsonKey(java.util.Map<String, Object> preferences) throws java.sql.SQLException {
        return this.users.findUsersByJsonKey(preferences);
    }

    public java.util.List<FindusersbyjsoncontainsRow> findUsersByJsonContains(java.util.Map<String, Object> preferences) throws java.sql.SQLException {
        return this.users.findUsersByJsonContains(preferences);
    }

    public java.util.List<GetuserswithtagRow> getUsersWithTag(java.util.List<String> tags) throws java.sql.SQLException {
        return this.users.getUsersWithTag(tags);
    }

    public java.util.List<GetuserswithanytagRow> getUsersWithAnyTag(java.util.List<String> tags) throws java.sql.SQLException {
        return this.users.getUsersWithAnyTag(tags);
    }

    public void addUserTag(java.util.List<String> tags, int id) throws java.sql.SQLException {
        this.users.addUserTag(tags, id);
    }

    public void removeUserTag(java.util.List<String> tags, int id) throws java.sql.SQLException {
        this.users.removeUserTag(tags, id);
    }

    public GetusershippingaddressRow getUserShippingAddress(int id) throws java.sql.SQLException {
        return this.users.getUserShippingAddress(id);
    }

    public void updateUserShipping(String shipping_field1, String shipping_field2, String shipping_field3, String shipping_field4, String shipping_field5, int id) throws java.sql.SQLException {
        this.users.updateUserShipping(shipping_field1, shipping_field2, shipping_field3, shipping_field4, shipping_field5, id);
    }

    public java.util.List<GetcomplexuseranalyticsRow> getComplexUserAnalytics(String total_posts, String total_comments, String limit) throws java.sql.SQLException {
        return this.users.getComplexUserAnalytics(total_posts, total_comments, limit);
    }

    public java.util.List<GetpostwithactivecommentersRow> getPostWithActiveCommenters(String rn, String post_id) throws java.sql.SQLException {
        return this.users.getPostWithActiveCommenters(rn, post_id);
    }

    public java.util.List<GetuserpostrankingsRow> getUserPostRankings(int limit) throws java.sql.SQLException {
        return this.users.getUserPostRankings(limit);
    }

    public java.util.List<GetusertrendingpostsRow> getUserTrendingPosts(int user_id, int limit) throws java.sql.SQLException {
        return this.users.getUserTrendingPosts(user_id, limit);
    }

    public GetpostcountbyuserRow getPostCountByUser(String user_id) throws java.sql.SQLException {
        return this.users.getPostCountByUser(user_id);
    }

    public java.util.List<GetuserswithmanypostsRow> getUsersWithManyPosts(int min_count) throws java.sql.SQLException {
        return this.users.getUsersWithManyPosts(min_count);
    }

    public java.util.List<GetpostswithcommentcountRow> getPostsWithCommentCount(int limit, int offset) throws java.sql.SQLException {
        return this.users.getPostsWithCommentCount(limit, offset);
    }

    public java.util.List<GetuserswithactivitylevelRow> getUsersWithActivityLevel() throws java.sql.SQLException {
        return this.users.getUsersWithActivityLevel();
    }

    public java.util.List<GetpostwithcommentsRow> getPostWithComments(int id) throws java.sql.SQLException {
        return this.users.getPostWithComments(id);
    }

    public GetpostdetailswithallrelationsRow getPostDetailsWithAllRelations(int id) throws java.sql.SQLException {
        return this.users.getPostDetailsWithAllRelations(id);
    }

    public Integer countUsersByRole(UserRole role) throws java.sql.SQLException {
        return this.users.countUsersByRole(role);
    }

    public CountusersRow countUsers() throws java.sql.SQLException {
        return this.users.countUsers();
    }

    public java.util.List<GetuserrolecountRow> getUserRoleCount() throws java.sql.SQLException {
        return this.users.getUserRoleCount();
    }

    public GetuseragestatsRow getUserAgeStats() throws java.sql.SQLException {
        return this.users.getUserAgeStats();
    }

    public java.util.List<GetpostsgroupedbystatusRow> getPostsGroupedByStatus(int count_threshold) throws java.sql.SQLException {
        return this.users.getPostsGroupedByStatus(count_threshold);
    }

    public java.util.List<GetdistinctcommentersRow> getDistinctCommenters() throws java.sql.SQLException {
        return this.users.getDistinctCommenters();
    }

    public java.util.List<GetlatestpostperuserRow> getLatestPostPerUser() throws java.sql.SQLException {
        return this.users.getLatestPostPerUser();
    }

    public java.util.List<SearchusersRow> searchUsers(String name, String email, int limit, int offset) throws java.sql.SQLException {
        return this.users.searchUsers(name, email, limit, offset);
    }

    public java.util.List<SearchpostsbytitleRow> searchPostsByTitle(String title, int limit, int offset) throws java.sql.SQLException {
        return this.users.searchPostsByTitle(title, limit, offset);
    }

    public java.util.List<FulltextsearchpostsRow> fullTextSearchPosts(String search_query, int limit) throws java.sql.SQLException {
        return this.users.fullTextSearchPosts(search_query, limit);
    }

    public java.util.List<GetuserregistrationstatsRow> getUserRegistrationStats() throws java.sql.SQLException {
        return this.users.getUserRegistrationStats();
    }

    public java.util.List<GetweeklypoststatsRow> getWeeklyPostStats(LocalDateTime created_at) throws java.sql.SQLException {
        return this.users.getWeeklyPostStats(created_at);
    }

    public java.util.List<Users> getUsersInIds(int id) throws java.sql.SQLException {
        return this.users.getUsersInIds(id);
    }

    public java.util.List<GetusersbynamesRow> getUsersByNames(String name1, String name2, String name3) throws java.sql.SQLException {
        return this.users.getUsersByNames(name1, name2, name3);
    }

    public java.util.List<GetuserswhocommentedRow> getUsersWhoCommented() throws java.sql.SQLException {
        return this.users.getUsersWhoCommented();
    }

    public java.util.List<GetuserswithnopostsRow> getUsersWithNoPosts() throws java.sql.SQLException {
        return this.users.getUsersWithNoPosts();
    }

    public java.util.List<GetallcontentbyuserRow> getAllContentByUser(int user_id, int limit) throws java.sql.SQLException {
        return this.users.getAllContentByUser(user_id, limit);
    }

    public java.util.List<ActiveUsers> getActiveUsers(int limit) throws java.sql.SQLException {
        return this.users.getActiveUsers(limit);
    }

    public java.util.List<UserActivitySummary> getUserActivitySummary(String post_count, String comment_count) throws java.sql.SQLException {
        return this.users.getUserActivitySummary(post_count, comment_count);
    }

    public void refreshPostStats() throws java.sql.SQLException {
        this.users.refreshPostStats();
    }

    public java.util.List<PostStats> getPostStats(int limit) throws java.sql.SQLException {
        return this.users.getPostStats(limit);
    }

    public java.util.List<GetusersubscriptionsRow> getUserSubscriptions(int user_id) throws java.sql.SQLException {
        return this.users.getUserSubscriptions(user_id);
    }

    public Subscriptions createSubscription(int user_id, SubscriptionTier tier, LocalDateTime expires_at, boolean auto_renew) throws java.sql.SQLException {
        return this.users.createSubscription(user_id, tier, expires_at, auto_renew);
    }

    public java.util.List<GetordersbyuserRow> getOrdersByUser(int user_id, int limit) throws java.sql.SQLException {
        return this.users.getOrdersByUser(user_id, limit);
    }

    public java.util.List<GetordersinstateRow> getOrdersInState(OrderState state, int limit) throws java.sql.SQLException {
        return this.users.getOrdersInState(state, limit);
    }

    public java.util.List<GetauditlogforuserRow> getAuditLogForUser(int changed_by, int limit, int offset) throws java.sql.SQLException {
        return this.users.getAuditLogForUser(changed_by, limit, offset);
    }

    public java.util.List<GetauditlogfortableRow> getAuditLogForTable(String table_name, int limit) throws java.sql.SQLException {
        return this.users.getAuditLogForTable(table_name, limit);
    }

    public GetdashboardstatsRow getDashboardStats() throws java.sql.SQLException {
        return this.users.getDashboardStats();
    }

    public java.util.List<GettopcommentersRow> getTopCommenters(int limit) throws java.sql.SQLException {
        return this.users.getTopCommenters(limit);
    }

    public java.util.List<GetengagementtimeseriesRow> getEngagementTimeSeries(LocalDateTime created_at) throws java.sql.SQLException {
        return this.users.getEngagementTimeSeries(created_at);
    }

    public Categories createCategory(String name) throws java.sql.SQLException {
        return this.users.createCategory(name);
    }

    public Posts createPost(int user_id, int category_id, String title, String content) throws java.sql.SQLException {
        return this.users.createPost(user_id, category_id, title, content);
    }

    public Comments createComment(int post_id, int user_id, String content) throws java.sql.SQLException {
        return this.users.createComment(post_id, user_id, content);
    }

    public void deleteOldUsers(LocalDateTime created_at) throws java.sql.SQLException {
        this.users.deleteOldUsers(created_at);
    }

    public void updateUserTimestamp(LocalDateTime updated_at, int id) throws java.sql.SQLException {
        this.users.updateUserTimestamp(updated_at, id);
    }

    public Notifications createNotification(int user_id, String type, String title, String body, java.util.Map<String, Object> metadata) throws java.sql.SQLException {
        return this.users.createNotification(user_id, type, title, body, metadata);
    }

    public java.util.List<Notifications> getNotificationsByUser(int user_id, int limit, int offset) throws java.sql.SQLException {
        return this.users.getNotificationsByUser(user_id, limit, offset);
    }

    public Integer getUnreadCount(int user_id) throws java.sql.SQLException {
        return this.users.getUnreadCount(user_id);
    }

    public void markNotificationRead(int id, int user_id) throws java.sql.SQLException {
        this.users.markNotificationRead(id, user_id);
    }

    public void markAllNotificationsRead(int user_id) throws java.sql.SQLException {
        this.users.markAllNotificationsRead(user_id);
    }

    public void deleteOldNotifications(int user_id, LocalDateTime created_at) throws java.sql.SQLException {
        this.users.deleteOldNotifications(user_id, created_at);
    }

    public java.util.List<GetnotificationsbytypeRow> getNotificationsByType(int user_id, String type, int limit) throws java.sql.SQLException {
        return this.users.getNotificationsByType(user_id, type, limit);
    }

    public Tags createTag(String name, String slug, String color) throws java.sql.SQLException {
        return this.users.createTag(name, slug, color);
    }

    public Tags getTagBySlug(String slug) throws java.sql.SQLException {
        return this.users.getTagBySlug(slug);
    }

    public java.util.List<Tags> getAllTags() throws java.sql.SQLException {
        return this.users.getAllTags();
    }

    public void addTagToPost(int post_id, int tag_id) throws java.sql.SQLException {
        this.users.addTagToPost(post_id, tag_id);
    }

    public void removeTagFromPost(int post_id, int tag_id) throws java.sql.SQLException {
        this.users.removeTagFromPost(post_id, tag_id);
    }

    public java.util.List<Tags> getTagsForPost(int post_id) throws java.sql.SQLException {
        return this.users.getTagsForPost(post_id);
    }

    public java.util.List<GetpostsbytagRow> getPostsByTag(String slug, int limit, int offset) throws java.sql.SQLException {
        return this.users.getPostsByTag(slug, limit, offset);
    }

    public java.util.List<GettoptagsRow> getTopTags(int limit) throws java.sql.SQLException {
        return this.users.getTopTags(limit);
    }

    public Media uploadMedia(int user_id, int post_id, String type, String url, long size_bytes, String mime_type, int width, int height, java.util.Map<String, Object> metadata) throws java.sql.SQLException {
        return this.users.uploadMedia(user_id, post_id, type, url, size_bytes, mime_type, width, height, metadata);
    }

    public java.util.List<GetmediabypostRow> getMediaByPost(int post_id) throws java.sql.SQLException {
        return this.users.getMediaByPost(post_id);
    }

    public java.util.List<GetmediabyuserRow> getMediaByUser(int user_id, int limit, int offset) throws java.sql.SQLException {
        return this.users.getMediaByUser(user_id, limit, offset);
    }

    public java.util.List<GetmediabytypeRow> getMediaByType(int user_id, String type) throws java.sql.SQLException {
        return this.users.getMediaByType(user_id, type);
    }

    public void deleteMedia(UUID id, int user_id) throws java.sql.SQLException {
        this.users.deleteMedia(id, user_id);
    }

    public GetstorageusedbyuserRow getStorageUsedByUser(int user_id) throws java.sql.SQLException {
        return this.users.getStorageUsedByUser(user_id);
    }

    public java.util.List<GetlargemediafilesRow> getLargeMediaFiles(long size_bytes, int limit) throws java.sql.SQLException {
        return this.users.getLargeMediaFiles(size_bytes, limit);
    }

    public java.util.List<GetuserfeedRow> getUserFeed(int user_id, int limit, int offset) throws java.sql.SQLException {
        return this.users.getUserFeed(user_id, limit, offset);
    }

    public java.util.List<SearchpostsfulltextRow> searchPostsFullText(String search_query, int limit) throws java.sql.SQLException {
        return this.users.searchPostsFullText(search_query, limit);
    }

    public void bulkMarkNotificationsRead(int user_id, int id) throws java.sql.SQLException {
        this.users.bulkMarkNotificationsRead(user_id, id);
    }

    public GetuserwithstatsRow getUserWithStats(int id) throws java.sql.SQLException {
        return this.users.getUserWithStats(id);
    }

    public void close() throws java.sql.SQLException {
        this.users.close();
    }
}
