// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.time.LocalDateTime;

public record SearchPostsByTitleRow(
    int id,
    String title,
    PostStatus status,
    LocalDateTime created_at
) {}
