// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.time.LocalDateTime;

public record Subscriptions(
    int id,
    int user_id,
    SubscriptionTier tier,
    LocalDateTime started_at,
    LocalDateTime expires_at,
    boolean auto_renew
) {}
