// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.util.UUID;
import java.sql.Connection;

public class TestsQueries {
    private final Connection conn;
    public TestsQueries(Connection conn) { this.conn = conn; }

    public CreateTesstsRow createTessts(UUID id, String name) throws java.sql.SQLException {
        final String sql = """
                insert into testss (id, name) values (?, ?) returning id, name
                """;
        try (java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setObject(1, id);
            stmt.setString(2, name);
            try (java.sql.ResultSet rs = stmt.executeQuery()) {
                if (!rs.next()) return null;
                return new CreateTesstsRow(
                    rs.getObject("id", java.util.UUID.class),
                    rs.getString("name")
                );
            }
        }
    }

    public java.util.List<Testss> gETTestss(UUID id) throws java.sql.SQLException {
        final String sql = """
                select * from testss where id = ?
                """;
        try (java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setObject(1, id);
            var items = new java.util.ArrayList<Testss>();
            try (java.sql.ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    items.add(new Testss(
                        rs.getObject("id", java.util.UUID.class),
                        rs.getObject("testting", java.util.UUID.class),
                        rs.getString("name"),
                        rs.getTimestamp("created_at") != null ? rs.getTimestamp("created_at").toLocalDateTime() : null
                    ));
                }
            }
            return items;
        }
    }

}
