// Code generated by FlashORM. DO NOT EDIT.

package java;


public record UpdateUserShippingArgs(
    String shipping_field1,
    String shipping_field2,
    String shipping_field3,
    String shipping_field4,
    String shipping_field5,
    int id
) {}
