// Code generated by FlashORM. DO NOT EDIT.

package java;


public record UploadMediaParams(
    int user_id,
    int post_id,
    String type,
    String url,
    long size_bytes,
    String mime_type,
    int width,
    int height,
    java.util.Map<String, Object> metadata
) {}
