// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.util.UUID;
import java.time.LocalDateTime;

public record UserSessions(
    UUID id,
    int user_id,
    String token,
    String ip_address,
    String user_agent,
    LocalDateTime expires_at,
    LocalDateTime created_at
) {}
