// Code generated by FlashORM. DO NOT EDIT.

package java;

import java.util.UUID;
import java.time.LocalDateTime;

public record Users(
    int id,
    String name,
    String address,
    boolean isadmin,
    Integer age,
    Integer age_range,
    String bio,
    String email,
    java.util.Map<String, Object> preferences,
    java.util.List<String> tags,
    UUID avatar_hash,
    String shipping,
    LocalDateTime created_at,
    LocalDateTime updated_at,
    UserRole role
) {}
