// Code generated by FlashORM. DO NOT EDIT.

package java;


public record UserActivitySummary(
    String id,
    String name,
    String email,
    String post_count,
    String comment_count,
    String last_post_at,
    String user_type
) {}
