// Code generated by FlashORM. DO NOT EDIT.
#![allow(unused_imports, dead_code)]

use chrono::{DateTime, Utc};
use uuid::Uuid;

use super::models::*;
use super::db::Queries;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPublishedPostsRow {
    pub id: Uuid,
    pub user_id: i32,
    pub title: String,
    pub body: Option<String>,
    pub views: i32,
    pub published: bool,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPostsByUserRow {
    pub id: Uuid,
    pub title: String,
    pub body: Option<String>,
    pub views: i32,
    pub published: bool,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SearchPostsByTitleRow {
    pub id: Uuid,
    pub title: String,
    pub views: i32,
    pub published: bool,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetTopPostsByViewsRow {
    pub id: Uuid,
    pub title: String,
    pub views: i32,
    pub user_id: i32,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListCommentsByPostRow {
    pub id: i32,
    pub user_id: i32,
    pub parent_id: Option<i32>,
    pub body: String,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetPostWithAuthorRow {
    pub id: Uuid,
    pub title: String,
    pub views: i32,
    pub created_at: DateTime<Utc>,
    pub author_name: String,
    pub author_email: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetPostWithTagsRow {
    pub id: Uuid,
    pub title: String,
    pub tag_name: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetUserPostsWithTagsRow {
    pub post_id: Uuid,
    pub title: String,
    pub views: i32,
    pub published: bool,
    pub tag_name: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetActivePostersRow {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub post_count: Option<i64>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetPopularTagsRow {
    pub id: i32,
    pub name: String,
    pub usage_count: Option<i64>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetUsersWithPublishedPostsRow {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetPostsAboveAvgViewsRow {
    pub id: Uuid,
    pub title: String,
    pub views: i32,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetUsersWithRecentActivityRow {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetUserStatsRow {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub post_count: Option<i64>,
    pub total_views: Option<i64>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetPostRanksByViewsRow {
    pub id: Uuid,
    pub title: String,
    pub views: i32,
    pub view_rank: Option<i64>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetUserPostTimelineRow {
    pub id: Uuid,
    pub title: String,
    pub views: i32,
    pub created_at: DateTime<Utc>,
    pub post_number: Option<i64>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetPostsByCategoryRow {
    pub id: Uuid,
    pub title: String,
    pub views: i32,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetCategoriesForPostRow {
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
}

pub struct CreatePostParams {
    pub user_id: i32,
    pub title: String,
    pub body: String,
}

pub struct UpdatePostParams {
    pub title: String,
    pub body: String,
    pub id: Uuid,
}

pub struct CreateCommentParams {
    pub post_id: Uuid,
    pub user_id: i32,
    pub parent_id: i32,
    pub body: String,
}

pub struct CreatePostWithCategoryParams {
    pub user_id: i32,
    pub title: String,
    pub body: String,
    pub published: bool,
}

pub struct CreateCategoryParams {
    pub name: String,
    pub description: String,
    pub parent_id: i32,
    pub sort_order: i32,
}

impl Queries {
    /// GetPost
    pub async fn get_post(
        &self,
        id: Uuid,
    ) -> Result<Posts, sqlx::Error> {
        sqlx::query_as!(Posts, "SELECT id, user_id, title, body, views, published, created_at, updated_at FROM posts WHERE id = $1;", id)
            .fetch_one(&self.pool)
            .await
    }

    /// ListPosts
    pub async fn list_posts(
        &self,
        limit: i64,
        offset: i64,
    ) -> Result<Vec<Posts>, sqlx::Error> {
        sqlx::query_as!(Posts, "SELECT id, user_id, title, body, views, published, created_at, updated_at FROM posts ORDER BY created_at DESC LIMIT $1 OFFSET $2;", limit, offset)
            .fetch_all(&self.pool)
            .await
    }

    /// ListPublishedPosts
    pub async fn list_published_posts(
        &self,
    ) -> Result<Vec<ListPublishedPostsRow>, sqlx::Error> {
        sqlx::query_as!(ListPublishedPostsRow, "SELECT id, user_id, title, body, views, published, created_at FROM posts WHERE published = TRUE ORDER BY created_at DESC;")
            .fetch_all(&self.pool)
            .await
    }

    /// ListPostsByUser
    pub async fn list_posts_by_user(
        &self,
        user_id: i32,
    ) -> Result<Vec<ListPostsByUserRow>, sqlx::Error> {
        sqlx::query_as!(ListPostsByUserRow, "SELECT id, title, body, views, published, created_at FROM posts WHERE user_id = $1 ORDER BY created_at DESC;", user_id)
            .fetch_all(&self.pool)
            .await
    }

    /// SearchPostsByTitle
    pub async fn search_posts_by_title(
        &self,
        title: &str,
    ) -> Result<Vec<SearchPostsByTitleRow>, sqlx::Error> {
        sqlx::query_as!(SearchPostsByTitleRow, "SELECT id, title, views, published, created_at FROM posts WHERE title ILIKE '%' || $1 || '%' ORDER BY views DESC;", title)
            .fetch_all(&self.pool)
            .await
    }

    /// CreatePost
    pub async fn create_post(
        &self,
        params: &CreatePostParams,
    ) -> Result<Posts, sqlx::Error> {
        sqlx::query_as!(Posts, "INSERT INTO posts (user_id, title, body) VALUES ($1, $2, $3) RETURNING id, user_id, title, body, views, published, created_at, updated_at;", params.user_id, params.title, params.body)
            .fetch_one(&self.pool)
            .await
    }

    /// UpdatePost
    pub async fn update_post(
        &self,
        params: &UpdatePostParams,
    ) -> Result<(), sqlx::Error> {
        sqlx::query!("UPDATE posts SET title = $1, body = $2, updated_at = NOW() WHERE id = $3;", params.title, params.body, params.id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    /// PublishPost
    pub async fn publish_post(
        &self,
        id: Uuid,
    ) -> Result<(), sqlx::Error> {
        sqlx::query!("UPDATE posts SET published = TRUE, updated_at = NOW() WHERE id = $1;", id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    /// DeletePost
    pub async fn delete_post(
        &self,
        id: Uuid,
    ) -> Result<(), sqlx::Error> {
        sqlx::query!("DELETE FROM posts WHERE id = $1;", id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    /// IncrementPostViews
    pub async fn increment_post_views(
        &self,
        id: Uuid,
    ) -> Result<sqlx::postgres::PgQueryResult, sqlx::Error> {
        sqlx::query!("UPDATE posts SET views = views + 1 WHERE id = $1;", id)
            .execute(&self.pool)
            .await
    }

    /// DeletePostsByUser
    pub async fn delete_posts_by_user(
        &self,
        user_id: i32,
    ) -> Result<sqlx::postgres::PgQueryResult, sqlx::Error> {
        sqlx::query!("DELETE FROM posts WHERE user_id = $1;", user_id)
            .execute(&self.pool)
            .await
    }

    /// CountPosts
    pub async fn count_posts(
        &self,
    ) -> Result<Option<i64>, sqlx::Error> {
        sqlx::query_scalar!("SELECT COUNT(*) FROM posts;")
            .fetch_one(&self.pool)
            .await
    }

    /// CountPublishedPosts
    pub async fn count_published_posts(
        &self,
    ) -> Result<Option<i64>, sqlx::Error> {
        sqlx::query_scalar!("SELECT COUNT(*) FROM posts WHERE published = TRUE;")
            .fetch_one(&self.pool)
            .await
    }

    /// CountPostsByUser
    pub async fn count_posts_by_user(
        &self,
        user_id: i32,
    ) -> Result<Option<i64>, sqlx::Error> {
        sqlx::query_scalar!("SELECT COUNT(*) FROM posts WHERE user_id = $1;", user_id)
            .fetch_one(&self.pool)
            .await
    }

    /// GetTopPostsByViews
    pub async fn get_top_posts_by_views(
        &self,
        limit: i64,
    ) -> Result<Vec<GetTopPostsByViewsRow>, sqlx::Error> {
        sqlx::query_as!(GetTopPostsByViewsRow, "SELECT id, title, views, user_id, created_at FROM posts WHERE published = TRUE ORDER BY views DESC LIMIT $1;", limit)
            .fetch_all(&self.pool)
            .await
    }

    /// GetComment
    pub async fn get_comment(
        &self,
        id: i32,
    ) -> Result<Comments, sqlx::Error> {
        sqlx::query_as!(Comments, "SELECT id, post_id, user_id, parent_id, body, created_at FROM comments WHERE id = $1;", id)
            .fetch_one(&self.pool)
            .await
    }

    /// ListCommentsByPost
    pub async fn list_comments_by_post(
        &self,
        post_id: Uuid,
    ) -> Result<Vec<ListCommentsByPostRow>, sqlx::Error> {
        sqlx::query_as!(ListCommentsByPostRow, "SELECT id, user_id, parent_id, body, created_at FROM comments WHERE post_id = $1 ORDER BY created_at ASC;", post_id)
            .fetch_all(&self.pool)
            .await
    }

    /// CreateComment
    pub async fn create_comment(
        &self,
        params: &CreateCommentParams,
    ) -> Result<Comments, sqlx::Error> {
        sqlx::query_as!(Comments, "INSERT INTO comments (post_id, user_id, parent_id, body) VALUES ($1, $2, $3, $4) RETURNING id, post_id, user_id, parent_id, body, created_at;", params.post_id, params.user_id, params.parent_id, params.body)
            .fetch_one(&self.pool)
            .await
    }

    /// DeleteComment
    pub async fn delete_comment(
        &self,
        id: i32,
    ) -> Result<(), sqlx::Error> {
        sqlx::query!("DELETE FROM comments WHERE id = $1;", id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    /// CountCommentsByPost
    pub async fn count_comments_by_post(
        &self,
        post_id: Uuid,
    ) -> Result<Option<i64>, sqlx::Error> {
        sqlx::query_scalar!("SELECT COUNT(*) FROM comments WHERE post_id = $1;", post_id)
            .fetch_one(&self.pool)
            .await
    }

    /// ListTags
    pub async fn list_tags(
        &self,
    ) -> Result<Vec<Tags>, sqlx::Error> {
        sqlx::query_as!(Tags, "SELECT id, name FROM tags ORDER BY name;")
            .fetch_all(&self.pool)
            .await
    }

    /// CreateTag
    pub async fn create_tag(
        &self,
        name: &str,
    ) -> Result<Tags, sqlx::Error> {
        sqlx::query_as!(Tags, "INSERT INTO tags (name) VALUES ($1) RETURNING id, name;", name)
            .fetch_one(&self.pool)
            .await
    }

    /// AddTagToPost
    pub async fn add_tag_to_post(
        &self,
        post_id: Uuid,
        tag_id: i32,
    ) -> Result<(), sqlx::Error> {
        sqlx::query!("INSERT INTO post_tags (post_id, tag_id) VALUES ($1, $2) ON CONFLICT DO NOTHING;", post_id, tag_id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    /// RemoveTagFromPost
    pub async fn remove_tag_from_post(
        &self,
        post_id: Uuid,
        tag_id: i32,
    ) -> Result<(), sqlx::Error> {
        sqlx::query!("DELETE FROM post_tags WHERE post_id = $1 AND tag_id = $2;", post_id, tag_id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    /// ListTagsForPost
    pub async fn list_tags_for_post(
        &self,
        post_id: Uuid,
    ) -> Result<Vec<Tags>, sqlx::Error> {
        sqlx::query_as!(Tags, "SELECT t.id, t.name FROM tags t JOIN post_tags pt ON pt.tag_id = t.id WHERE pt.post_id = $1 ORDER BY t.name;", post_id)
            .fetch_all(&self.pool)
            .await
    }

    /// GetPostWithAuthor
    pub async fn get_post_with_author(
        &self,
        limit: i64,
        offset: i64,
    ) -> Result<Vec<GetPostWithAuthorRow>, sqlx::Error> {
        sqlx::query_as!(GetPostWithAuthorRow, "SELECT p.id, p.title, p.views, p.created_at, u.name AS author_name, u.email AS author_email FROM posts p JOIN users u ON u.id = p.user_id WHERE p.published = TRUE ORDER BY p.created_at DESC LIMIT $1 OFFSET $2;", limit, offset)
            .fetch_all(&self.pool)
            .await
    }

    /// GetPostWithTags
    pub async fn get_post_with_tags(
        &self,
        id: Uuid,
    ) -> Result<Vec<GetPostWithTagsRow>, sqlx::Error> {
        sqlx::query_as!(GetPostWithTagsRow, "SELECT p.id, p.title, t.name AS tag_name FROM posts p JOIN post_tags pt ON pt.post_id = p.id JOIN tags t ON t.id = pt.tag_id WHERE p.id = $1 ORDER BY t.name;", id)
            .fetch_all(&self.pool)
            .await
    }

    /// GetUserPostsWithTags
    pub async fn get_user_posts_with_tags(
        &self,
        user_id: i32,
    ) -> Result<Vec<GetUserPostsWithTagsRow>, sqlx::Error> {
        sqlx::query_as!(GetUserPostsWithTagsRow, "SELECT p.id AS post_id, p.title, p.views, p.published, t.name AS tag_name FROM posts p JOIN post_tags pt ON pt.post_id = p.id JOIN tags t ON t.id = pt.tag_id WHERE p.user_id = $1 ORDER BY p.created_at DESC;", user_id)
            .fetch_all(&self.pool)
            .await
    }

    /// GetActivePosters
    pub async fn get_active_posters(
        &self,
        count_threshold: i64,
    ) -> Result<Vec<GetActivePostersRow>, sqlx::Error> {
        sqlx::query_as!(GetActivePostersRow, "SELECT u.id, u.name, u.email, COUNT(p.id) AS post_count FROM users u JOIN posts p ON p.user_id = u.id WHERE p.published = TRUE GROUP BY u.id, u.name, u.email HAVING COUNT(p.id) >= $1 ORDER BY post_count DESC;", count_threshold)
            .fetch_all(&self.pool)
            .await
    }

    /// GetPopularTags
    pub async fn get_popular_tags(
        &self,
        count_threshold: i64,
    ) -> Result<Vec<GetPopularTagsRow>, sqlx::Error> {
        sqlx::query_as!(GetPopularTagsRow, "SELECT t.id, t.name, COUNT(pt.post_id) AS usage_count FROM tags t JOIN post_tags pt ON pt.tag_id = t.id GROUP BY t.id, t.name HAVING COUNT(pt.post_id) >= $1 ORDER BY usage_count DESC;", count_threshold)
            .fetch_all(&self.pool)
            .await
    }

    /// GetUsersWithPublishedPosts
    pub async fn get_users_with_published_posts(
        &self,
    ) -> Result<Vec<GetUsersWithPublishedPostsRow>, sqlx::Error> {
        sqlx::query_as!(GetUsersWithPublishedPostsRow, "SELECT id, name, email, created_at FROM users WHERE id IN (SELECT DISTINCT user_id FROM posts WHERE published = TRUE) ORDER BY name;")
            .fetch_all(&self.pool)
            .await
    }

    /// GetPostsAboveAvgViews
    pub async fn get_posts_above_avg_views(
        &self,
    ) -> Result<Vec<GetPostsAboveAvgViewsRow>, sqlx::Error> {
        sqlx::query_as!(GetPostsAboveAvgViewsRow, "SELECT id, title, views, created_at FROM posts WHERE published = TRUE AND views > (SELECT AVG(views) FROM posts WHERE published = TRUE) ORDER BY views DESC;")
            .fetch_all(&self.pool)
            .await
    }

    /// GetUsersWithRecentActivity
    pub async fn get_users_with_recent_activity(
        &self,
    ) -> Result<Vec<GetUsersWithRecentActivityRow>, sqlx::Error> {
        sqlx::query_as!(GetUsersWithRecentActivityRow, "SELECT id, name, email, created_at FROM users WHERE id IN ( SELECT DISTINCT user_id FROM posts WHERE created_at > NOW() - INTERVAL '30 days' UNION SELECT DISTINCT user_id FROM comments WHERE created_at > NOW() - INTERVAL '30 days' ) ORDER BY name;")
            .fetch_all(&self.pool)
            .await
    }

    /// DeactivateUsersWithNoPosts
    pub async fn deactivate_users_with_no_posts(
        &self,
    ) -> Result<sqlx::postgres::PgQueryResult, sqlx::Error> {
        sqlx::query!("UPDATE users SET is_active = FALSE, updated_at = NOW() WHERE id NOT IN (SELECT DISTINCT user_id FROM posts);")
            .execute(&self.pool)
            .await
    }

    /// DeleteUnpublishedPostsOlderThan
    pub async fn delete_unpublished_posts_older_than(
        &self,
    ) -> Result<sqlx::postgres::PgQueryResult, sqlx::Error> {
        sqlx::query!("DELETE FROM posts WHERE published = FALSE AND created_at < NOW() - INTERVAL '90 days';")
            .execute(&self.pool)
            .await
    }

    /// BoostPopularPosts
    pub async fn boost_popular_posts(
        &self,
        limit: i64,
    ) -> Result<sqlx::postgres::PgQueryResult, sqlx::Error> {
        sqlx::query!("UPDATE posts SET views = views + 100 WHERE id IN ( SELECT id FROM posts WHERE published = TRUE ORDER BY views DESC LIMIT $1 );", limit)
            .execute(&self.pool)
            .await
    }

    /// GetUserStats
    pub async fn get_user_stats(
        &self,
        limit: i64,
    ) -> Result<Vec<GetUserStatsRow>, sqlx::Error> {
        sqlx::query_as!(GetUserStatsRow, "WITH user_post_counts AS ( SELECT user_id, COUNT(*) AS post_count, SUM(views) AS total_views FROM posts WHERE published = TRUE GROUP BY user_id ) SELECT u.id, u.name, u.email, upc.post_count, upc.total_views FROM users u JOIN user_post_counts upc ON upc.user_id = u.id ORDER BY upc.total_views DESC LIMIT $1;", limit)
            .fetch_all(&self.pool)
            .await
    }

    /// GetPostRanksByViews
    pub async fn get_post_ranks_by_views(
        &self,
        limit: i64,
    ) -> Result<Vec<GetPostRanksByViewsRow>, sqlx::Error> {
        sqlx::query_as!(GetPostRanksByViewsRow, "SELECT id, title, views, RANK() OVER (ORDER BY views DESC) AS view_rank FROM posts WHERE published = TRUE ORDER BY view_rank LIMIT $1;", limit)
            .fetch_all(&self.pool)
            .await
    }

    /// GetUserPostTimeline
    pub async fn get_user_post_timeline(
        &self,
        user_id: i32,
    ) -> Result<Vec<GetUserPostTimelineRow>, sqlx::Error> {
        sqlx::query_as!(GetUserPostTimelineRow, "SELECT id, title, views, created_at, ROW_NUMBER() OVER (ORDER BY created_at) AS post_number FROM posts WHERE user_id = $1 AND published = TRUE ORDER BY created_at;", user_id)
            .fetch_all(&self.pool)
            .await
    }

    /// CreatePostWithCategory
    pub async fn create_post_with_category(
        &self,
        params: &CreatePostWithCategoryParams,
    ) -> Result<Posts, sqlx::Error> {
        sqlx::query_as!(Posts, "INSERT INTO posts (user_id, title, body, published) VALUES ($1, $2, $3, $4) RETURNING id, user_id, title, body, views, published, created_at, updated_at;", params.user_id, params.title, params.body, params.published)
            .fetch_one(&self.pool)
            .await
    }

    /// BulkPublishUserPosts
    pub async fn bulk_publish_user_posts(
        &self,
        user_id: i32,
    ) -> Result<sqlx::postgres::PgQueryResult, sqlx::Error> {
        sqlx::query!("UPDATE posts SET published = TRUE, updated_at = NOW() WHERE user_id = $1 AND published = FALSE;", user_id)
            .execute(&self.pool)
            .await
    }

    /// ListCategories
    pub async fn list_categories(
        &self,
    ) -> Result<Vec<Categories>, sqlx::Error> {
        sqlx::query_as!(Categories, "SELECT id, name, description, parent_id, sort_order, created_at FROM categories ORDER BY sort_order, name;")
            .fetch_all(&self.pool)
            .await
    }

    /// CreateCategory
    pub async fn create_category(
        &self,
        params: &CreateCategoryParams,
    ) -> Result<Categories, sqlx::Error> {
        sqlx::query_as!(Categories, "INSERT INTO categories (name, description, parent_id, sort_order) VALUES ($1, $2, $3, $4) RETURNING id, name, description, parent_id, sort_order, created_at;", params.name, params.description, params.parent_id, params.sort_order)
            .fetch_one(&self.pool)
            .await
    }

    /// AddPostToCategory
    pub async fn add_post_to_category(
        &self,
        post_id: Uuid,
        category_id: i32,
    ) -> Result<(), sqlx::Error> {
        sqlx::query!("INSERT INTO post_categories (post_id, category_id) VALUES ($1, $2) ON CONFLICT DO NOTHING;", post_id, category_id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    /// RemovePostFromCategory
    pub async fn remove_post_from_category(
        &self,
        post_id: Uuid,
        category_id: i32,
    ) -> Result<(), sqlx::Error> {
        sqlx::query!("DELETE FROM post_categories WHERE post_id = $1 AND category_id = $2;", post_id, category_id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    /// GetPostsByCategory
    pub async fn get_posts_by_category(
        &self,
        category_id: i32,
    ) -> Result<Vec<GetPostsByCategoryRow>, sqlx::Error> {
        sqlx::query_as!(GetPostsByCategoryRow, "SELECT p.id, p.title, p.views, p.created_at FROM posts p JOIN post_categories pc ON pc.post_id = p.id WHERE pc.category_id = $1 AND p.published = TRUE ORDER BY p.created_at DESC;", category_id)
            .fetch_all(&self.pool)
            .await
    }

    /// GetCategoriesForPost
    pub async fn get_categories_for_post(
        &self,
        post_id: Uuid,
    ) -> Result<Vec<GetCategoriesForPostRow>, sqlx::Error> {
        sqlx::query_as!(GetCategoriesForPostRow, "SELECT c.id, c.name, c.description FROM categories c JOIN post_categories pc ON pc.category_id = c.id WHERE pc.post_id = $1 ORDER BY c.name;", post_id)
            .fetch_all(&self.pool)
            .await
    }

}
