// Code generated by FlashORM. DO NOT EDIT.

/** JSON type for column 'preferences'. Parse with: JSON.parse(row.preferences) as Preferences */
export interface Preferences {
  theme: string | null;
  notifications: boolean | null;
  language: string | null;
  font_size: number | null;
}

/** JSON type for column 'metadata'. Parse with: JSON.parse(row.metadata) as Metadata */
export interface Metadata {
  views: number | null;
  shares: number | null;
  bookmarks: number | null;
  avg_read_time: number | null;
  tags_used: string[] | null;
}

export interface Users {
  id: number;
  name: string;
  address: string | null;
  isadmin: boolean;
  age: number | null;
  age_range: number | null;
  bio: string | null;
  email: string;
  preferences: Object | null;
  tags: string[] | null;
  avatar_hash: string | null;
  shipping: string | null;
  created_at: Date;
  updated_at: Date;
  role: 'admin' | 'moderator' | 'user' | 'guest';
}

export interface Categories {
  id: number;
  name: string;
  slug: string | null;
  color: string | null;
  metadata: Object | null;
  created_at: Date;
}

export interface Posts {
  id: number;
  user_id: number;
  category_id: number;
  title: string;
  content: string;
  excerpt: string | null;
  tags: string[] | null;
  metadata: Object | null;
  view_count: number;
  is_featured: boolean;
  published_at: Date | null;
  created_at: Date;
  updated_at: Date;
  status: 'draft' | 'published' | 'archived';
}

export interface Comments {
  id: number;
  post_id: number;
  user_id: number;
  parent_id: number | null;
  content: string;
  created_at: Date;
}

export interface Subscriptions {
  id: number;
  user_id: number;
  tier: 'free' | 'pro' | 'enterprise';
  started_at: Date;
  expires_at: Date | null;
  auto_renew: boolean;
}

export interface Orders {
  id: string;
  user_id: number;
  total_amount: number;
  discount_pct: string | null;
  shipping_addr: string;
  line_items: Object;
  state: 'pending' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  placed_at: Date;
  updated_at: Date;
}

export interface AuditLog {
  id: number;
  table_name: string;
  record_id: string;
  action: string;
  old_data: Object | null;
  new_data: Object | null;
  changed_by: number | null;
  changed_at: Date;
}

export interface UserSessions {
  id: string;
  user_id: number;
  token: string;
  ip_address: string | null;
  user_agent: string | null;
  expires_at: Date;
  created_at: Date;
}

export interface Notifications {
  id: number;
  user_id: number;
  type: string;
  title: string;
  body: string;
  is_read: boolean;
  metadata: Object | null;
  created_at: Date;
}

export interface Tags {
  id: number;
  name: string;
  slug: string;
  color: string | null;
}

export interface PostTags {
  post_id: number;
  tag_id: number;
}

export interface Media {
  id: string;
  user_id: number;
  post_id: number | null;
  type: string;
  url: string;
  size_bytes: number;
  mime_type: string;
  width: number | null;
  height: number | null;
  metadata: Object | null;
  created_at: Date;
}

export interface ActiveUsers {
  id: string | null;
  name: string | null;
  email: string | null;
  role: string | null;
  created_at: string | null;
}

export interface UserActivitySummary {
  id: string | null;
  name: string | null;
  email: string | null;
  post_count: string | null;
  comment_count: string | null;
  last_post_at: string | null;
  user_type: string | null;
}

export interface PostStats {
  post_id: string | null;
  title: string | null;
  comment_count: string | null;
  unique_commenters: string | null;
  last_comment_at: string | null;
}

export interface GetUserDisplayInfoResult {
  id: number;
  name: string;
  email: string;
  display_address: string;
  age: string;
  bio: string;
}

export interface GetWeeklyPostStatsResult {
  week_start: string;
  posts_created: number;
  total_views: number | null;
}

export interface FindUsersByJsonContainsResult {
  id: number;
  name: string;
  email: string;
}

export interface GetUserTrendingPostsResult {
  id: number;
  title: string;
  user_id: number;
  view_count: number;
  created_at: Date;
  prev_view_count: number;
  next_view_count: number;
  view_delta: number | null;
}

export interface GetUserAgeStatsResult {
  first_joined: Date | null;
  last_joined: Date | null;
  total: number;
  avg_age: number | null;
  avg_name_length: number | null;
}

export interface GetOrdersByUserResult {
  id: string;
  total_amount: number;
  discount_pct: string | null;
  state: 'pending' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  shipping_addr: string;
  placed_at: Date;
}

export interface GetTopCommentersResult {
  id: number;
  name: string;
  email: string;
  comment_count: number;
  rank: number;
}

export interface GetUserRegistrationStatsResult {
  year: number | null;
  month: number | null;
  signups: number;
}

export interface GetDashboardStatsResult {
  total_users: number;
  total_posts: number;
  total_comments: number;
  published_posts: number;
  posts_this_week: number;
  signups_this_week: number;
  comments_last_24h: number;
  pending_orders: number;
}

export interface GetMediaByTypeResult {
  id: string;
  user_id: number;
  url: string;
  size_bytes: number;
  mime_type: string;
  created_at: Date;
}

export interface GetUserPrefsResult {
  id: number;
  name: string;
  email: string;
  preferences: Preferences | null;
}

export interface GetUsersWithBioResult {
  id: number;
  name: string;
  email: string;
  bio: string;
}

export interface SearchUsersWithCOALESCEResult {
  id: number;
  name: string;
  email: string;
  bio_text: string;
}

export interface GetComplexUserAnalyticsResult {
  id: number;
  name: string;
  email: string;
  role: 'admin' | 'moderator' | 'user' | 'guest';
  isadmin: boolean;
  user_created_at: Date;
  total_posts: number;
  published_posts: number;
  draft_posts: number;
  total_comments: number;
  posts_commented_on: number;
  categories_used: number;
  category_names: string;
  last_post_date: Date | null;
  last_comment_date: Date | null;
  avg_post_length: number;
  activity_level: string;
  engagement_score: number;
}

export interface GetPostWithActiveCommentersResult {
  commenter_name: string;
  last_comment_at: string | null;
}

export interface ListPostsWithMetaResult {
  id: number;
  title: string;
  status: 'draft' | 'published' | 'archived';
  view_count: number;
  metadata: Metadata | null;
  created_at: Date;
}

export interface GetUsersCreatedBetweenResult {
  id: number;
  name: string;
  email: string;
  created_at: Date;
}

export interface FindUsersByJsonKeyResult {
  id: number;
  name: string;
  email: string;
  preferences: Object | null;
}

export interface GetPostMetaResult {
  id: number;
  title: string;
  status: 'draft' | 'published' | 'archived';
  metadata: Metadata | null;
  user_id: number;
  created_at: Date;
}

export interface GetUserPreferencesResult {
  id: number;
  name: string;
  preferences: Object | null;
}

export interface GetUsersWithTagResult {
  id: number;
  name: string;
  email: string;
  tags: string[] | null;
}

export interface GetPostCountByUserResult {
  post_count: number;
  comment_count: number;
}

export interface SetUserPrefsResult {
  id: number;
  name: string;
  preferences: Preferences | null;
  updated_at: Date;
}

export interface FullTextSearchPostsResult {
  id: number;
  title: string;
  rank: number | null;
}

export interface GetUsersWithNoPostsResult {
  id: number;
  name: string;
  email: string;
}

export interface GetNotificationsByTypeResult {
  id: number;
  type: string;
  title: string;
  body: string;
  is_read: boolean;
  created_at: Date;
}

export interface GetLargeMediaFilesResult {
  id: string;
  user_id: number;
  type: string;
  url: string;
  size_bytes: number;
  mime_type: string;
  created_at: Date;
}

export interface GetUserWithStatsResult {
  published_posts: number;
  total_comments: number;
  unread_notifications: number;
  storage_used: number | null;
}

export interface GetUsersByGeneratedRangeResult {
  id: number;
  name: string;
  age: number | null;
  age_range: number | null;
}

export interface GetUserPostRankingsResult {
  id: number;
  name: string;
  post_count: number;
  post_rank: number;
  dense_post_rank: number;
  row_num: number;
}

export interface GetUserRoleCountResult {
  role: 'admin' | 'moderator' | 'user' | 'guest';
  count: number;
}

export interface GetUsersByNamesResult {
  id: number;
  name: string;
  email: string;
}

export interface GetUsersWhoCommentedResult {
  id: number;
  name: string;
  email: string;
}

export interface GetOrdersInStateResult {
  id: string;
  user_id: number;
  user_name: string;
  total_amount: number;
  state: 'pending' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  placed_at: Date;
}

export interface GetAuditLogForTableResult {
  id: number;
  table_name: string;
  record_id: string;
  action: string;
  changed_by: number | null;
  changed_at: Date;
}

export interface GetPostsByTagResult {
  id: number;
  title: string;
  status: 'draft' | 'published' | 'archived';
  created_at: Date;
  author_name: string;
  comment_count: number;
}

export interface GetUserFeedResult {
  id: number;
  title: string;
  excerpt: string | null;
  status: 'draft' | 'published' | 'archived';
  created_at: Date;
  author_id: number;
  author_name: string;
  avatar_hash: string | null;
  comment_count: number;
  tag_count: number;
}

export interface GetUsersWithAnyTagResult {
  id: number;
  name: string;
  email: string;
  tags: string[] | null;
}

export interface GetPostsWithCommentCountResult {
  id: number;
  title: string;
  created_at: Date;
  comment_count: number;
  unique_commenters: number;
  last_comment_at: Date | null;
}

export interface CountUsersResult {
  total_users: number;
  admin_count: number;
  regular_count: number;
}

export interface SearchPostsByTitleResult {
  id: number;
  title: string;
  status: 'draft' | 'published' | 'archived';
  created_at: Date;
}

export interface GetAuditLogForUserResult {
  id: number;
  table_name: string;
  record_id: string;
  action: string;
  old_data: Object | null;
  new_data: Object | null;
  changed_at: Date;
}

export interface GetMediaByUserResult {
  id: string;
  type: string;
  url: string;
  size_bytes: number;
  mime_type: string;
  created_at: Date;
}

export interface GetStorageUsedByUserResult {
  total_bytes: number | null;
  total_files: number;
  image_count: number;
  video_count: number;
  document_count: number;
}

export interface GetUsersWithNullAddressResult {
  id: number;
  name: string;
  email: string;
}

export interface GetUsersByAgeRangeResult {
  id: number;
  name: string;
  age: number | null;
  age_range: number | null;
}

export interface GetPostWithCommentsResult {
  post_id: number;
  title: string;
  content: string;
  author: string;
  comment_text: string;
  commenter: string;
}

export interface GetUserSubscriptionsResult {
  id: number;
  tier: 'free' | 'pro' | 'enterprise';
  started_at: Date;
  expires_at: Date | null;
  auto_renew: boolean;
}

export interface SearchPostsFullTextResult {
  id: number;
  title: string;
  excerpt: string | null;
  status: 'draft' | 'published' | 'archived';
  created_at: Date;
  author_name: string;
  rank: number | null;
}

export interface GetUsersWithManyPostsResult {
  id: number;
  name: string;
  email: string;
  total_posts: number;
}

export interface GetEngagementTimeSeriesResult {
  day: string;
  count: number;
  event_type: string;
}

export interface GetTopTagsResult {
  id: number;
  name: string;
  slug: string;
  color: string | null;
  post_count: number;
}

export interface GetUsersWithActivityLevelResult {
  id: number;
  name: string;
  email: string;
  created_at: Date;
  account_age_category: string;
  effective_role: string;
}

export interface GetDistinctCommentersResult {
  id: number;
  name: string;
  email: string;
}

export interface GetLatestPostPerUserResult {
  user_id: number;
  post_id: number;
  title: string;
  status: 'draft' | 'published' | 'archived';
  created_at: Date;
}

export interface GetAllContentByUserResult {
  content_type: string;
  content_id: string;
  content_summary: string;
  created_at: Date;
}

export interface GetUserShippingAddressResult {
  id: number;
  name: string;
  shipping: string | null;
  shipping_city: string;
  shipping_country: string;
}

export interface GetPostDetailsWithAllRelationsResult {
  id: number;
  title: string;
  content: string;
  status: 'draft' | 'published' | 'archived';
  created_at: Date;
  updated_at: Date;
  author_id: number;
  author_name: string;
  author_email: string;
  author_role: 'admin' | 'moderator' | 'user' | 'guest';
  author_is_admin: boolean;
  category_id: number;
  category_name: string;
  comment_count: number;
  unique_commenters: number;
  all_comments: string | null;
  commenter_names: string[] | null;
  last_comment_date: Date | null;
  content_length: number | null;
  hours_since_created: number | null;
}

export interface GetMediaByPostResult {
  id: string;
  type: string;
  url: string;
  size_bytes: number;
  mime_type: string;
  width: number | null;
  height: number | null;
  created_at: Date;
}

export interface ListUsersWithPrefsResult {
  id: number;
  name: string;
  email: string;
  preferences: Preferences | null;
  created_at: Date;
}

export interface GetPostsGroupedByStatusResult {
  status: 'draft' | 'published' | 'archived';
  count: number;
  oldest: Date | null;
  newest: Date | null;
}

export interface SearchUsersResult {
  id: number;
  name: string;
  email: string;
}

export interface GetTagsForPostResult {
  id: number;
  name: string;
  slug: string;
  color: string | null;
}

export interface CreateUserFullParams {
  name: string;
  email: string;
  age: number;
  bio: string;
  preferences: Object;
  tags: string[];
  role: 'admin' | 'moderator' | 'user' | 'guest';
}

export interface UpsertUserParams {
  name: string;
  email: string;
  role: 'admin' | 'moderator' | 'user' | 'guest';
}

export interface UpsertUserWithCOALESCEParams {
  name: string;
  email: string;
  bio: string;
}

export interface SearchUsersWithCOALESCEParams {
  name: string;
  email: string;
  name2: string;
  limit: number;
  offset: number;
}

export interface GetRecentUsersParams {
  created_at: Date;
  limit: number;
  offset: number;
}

export interface UpdateUserShippingParams {
  shipping_field1: string;
  shipping_field2: string;
  shipping_field3: string;
  shipping_field4: string;
  shipping_field5: string;
  id: number;
}

export interface GetComplexUserAnalyticsParams {
  total_posts: string;
  total_comments: string;
  limit: number;
}

export interface SearchUsersParams {
  name: string;
  email: string;
  limit: number;
  offset: number;
}

export interface SearchPostsByTitleParams {
  title: string;
  limit: number;
  offset: number;
}

export interface CreateSubscriptionParams {
  user_id: number;
  tier: 'free' | 'pro' | 'enterprise';
  expires_at: Date;
  auto_renew: boolean;
}

export interface GetAuditLogForUserParams {
  changed_by: number;
  limit: number;
  offset: number;
}

export interface CreatePostParams {
  user_id: number;
  category_id: number;
  title: string;
  content: string;
}

export interface CreateCommentParams {
  post_id: number;
  user_id: number;
  content: string;
}

export interface CreateNotificationParams {
  user_id: number;
  type: string;
  title: string;
  body: string;
  metadata: Object;
}

export interface GetNotificationsByUserParams {
  user_id: number;
  limit: number;
  offset: number;
}

export interface GetNotificationsByTypeParams {
  user_id: number;
  type: string;
  limit: number;
}

export interface CreateTagParams {
  name: string;
  slug: string;
  color: string;
}

export interface GetPostsByTagParams {
  slug: string;
  limit: number;
  offset: number;
}

export interface UploadMediaParams {
  user_id: number;
  post_id: number;
  type: string;
  url: string;
  size_bytes: number;
  mime_type: string;
  width: number;
  height: number;
  metadata: Object;
}

export interface GetMediaByUserParams {
  user_id: number;
  limit: number;
  offset: number;
}

export interface GetUserFeedParams {
  user_id: number;
  limit: number;
  offset: number;
}

export class Queries {
  constructor(db: any);

  getUserPrefs(id: number): Promise<GetUserPrefsResult | null>;
  setUserPrefs(preferences: Object, id: number): Promise<SetUserPrefsResult | null>;
  getPostMeta(id: number): Promise<GetPostMetaResult | null>;
  listUsersWithPrefs(limit: number): Promise<ListUsersWithPrefsResult[]>;
  listPostsWithMeta(user_id: number): Promise<ListPostsWithMetaResult[]>;
  createUser(name: string, email: string): Promise<Users | null>;
  createUserFull(args: CreateUserFullParams): Promise<Users | null>;
  getUser(id: number): Promise<Users | null>;
  getUserByEmail(email: string): Promise<Users | null>;
  updateUserName(name: string, id: number): Promise<Users | null>;
  updateUserRole(role: 'admin' | 'moderator' | 'user' | 'guest', id: number): Promise<number>;
  deleteUser(id: number): Promise<number>;
  listUsers(limit: number, offset: number): Promise<Users[]>;
  upsertUser(args: UpsertUserParams): Promise<Users | null>;
  upsertUserWithCOALESCE(args: UpsertUserWithCOALESCEParams): Promise<Users | null>;
  getUsersWithNullAddress(): Promise<GetUsersWithNullAddressResult[]>;
  getUsersWithBio(): Promise<GetUsersWithBioResult[]>;
  getUserDisplayInfo(id: number): Promise<GetUserDisplayInfoResult | null>;
  searchUsersWithCOALESCE(args: SearchUsersWithCOALESCEParams): Promise<SearchUsersWithCOALESCEResult[]>;
  getUsersCreatedBetween(created_at_start: Date, created_at_end: Date): Promise<GetUsersCreatedBetweenResult[]>;
  getUsersByAgeRange(age_start: number, age_end: number): Promise<GetUsersByAgeRangeResult[]>;
  getUsersByGeneratedRange(age_range: number): Promise<GetUsersByGeneratedRangeResult[]>;
  getRecentUsers(args: GetRecentUsersParams): Promise<Users[]>;
  getUserPreferences(id: number): Promise<GetUserPreferencesResult | null>;
  updateUserPreferences(preferences: Object, id: number): Promise<number>;
  findUsersByJsonKey(preferences: Object): Promise<FindUsersByJsonKeyResult[]>;
  findUsersByJsonContains(preferences: Object): Promise<FindUsersByJsonContainsResult[]>;
  getUsersWithTag(tags: string): Promise<GetUsersWithTagResult[]>;
  getUsersWithAnyTag(tags: string): Promise<GetUsersWithAnyTagResult[]>;
  addUserTag(tags: string[], id: number): Promise<number>;
  removeUserTag(tags: string[], id: number): Promise<number>;
  getUserShippingAddress(id: number): Promise<GetUserShippingAddressResult | null>;
  updateUserShipping(args: UpdateUserShippingParams): Promise<number>;
  getComplexUserAnalytics(args: GetComplexUserAnalyticsParams): Promise<GetComplexUserAnalyticsResult[]>;
  getPostWithActiveCommenters(rn: string, post_id: number): Promise<GetPostWithActiveCommentersResult[]>;
  getUserPostRankings(limit: number): Promise<GetUserPostRankingsResult[]>;
  getUserTrendingPosts(user_id: number, limit: number): Promise<GetUserTrendingPostsResult[]>;
  getPostCountByUser(user_id: number): Promise<GetPostCountByUserResult | null>;
  getUsersWithManyPosts(min_count: number): Promise<GetUsersWithManyPostsResult[]>;
  getPostsWithCommentCount(limit: number, offset: number): Promise<GetPostsWithCommentCountResult[]>;
  getUsersWithActivityLevel(): Promise<GetUsersWithActivityLevelResult[]>;
  getPostWithComments(id: number): Promise<GetPostWithCommentsResult[]>;
  getPostDetailsWithAllRelations(id: number): Promise<GetPostDetailsWithAllRelationsResult | null>;
  countUsersByRole(role: 'admin' | 'moderator' | 'user' | 'guest'): Promise<number | null>;
  countUsers(): Promise<CountUsersResult | null>;
  getUserRoleCount(): Promise<GetUserRoleCountResult[]>;
  getUserAgeStats(): Promise<GetUserAgeStatsResult | null>;
  getPostsGroupedByStatus(count_threshold: number): Promise<GetPostsGroupedByStatusResult[]>;
  getDistinctCommenters(): Promise<GetDistinctCommentersResult[]>;
  getLatestPostPerUser(): Promise<GetLatestPostPerUserResult[]>;
  searchUsers(args: SearchUsersParams): Promise<SearchUsersResult[]>;
  searchPostsByTitle(args: SearchPostsByTitleParams): Promise<SearchPostsByTitleResult[]>;
  fullTextSearchPosts(search_query: string, limit: number): Promise<FullTextSearchPostsResult[]>;
  getUserRegistrationStats(): Promise<GetUserRegistrationStatsResult[]>;
  getWeeklyPostStats(created_at: Date): Promise<GetWeeklyPostStatsResult[]>;
  getUsersInIds(id: number): Promise<Users[]>;
  getUsersByNames(name: string): Promise<GetUsersByNamesResult[]>;
  getUsersWhoCommented(): Promise<GetUsersWhoCommentedResult[]>;
  getUsersWithNoPosts(): Promise<GetUsersWithNoPostsResult[]>;
  getAllContentByUser(user_id: number, limit: number): Promise<GetAllContentByUserResult[]>;
  getActiveUsers(limit: number): Promise<ActiveUsers[]>;
  getUserActivitySummary(post_count: number, comment_count: number): Promise<UserActivitySummary[]>;
  refreshPostStats(): Promise<number>;
  getPostStats(limit: number): Promise<PostStats[]>;
  getUserSubscriptions(user_id: number): Promise<GetUserSubscriptionsResult[]>;
  createSubscription(args: CreateSubscriptionParams): Promise<Subscriptions | null>;
  getOrdersByUser(user_id: number, limit: number): Promise<GetOrdersByUserResult[]>;
  getOrdersInState(state: 'pending' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled' | 'refunded', limit: number): Promise<GetOrdersInStateResult[]>;
  getAuditLogForUser(args: GetAuditLogForUserParams): Promise<GetAuditLogForUserResult[]>;
  getAuditLogForTable(table_name: string, limit: number): Promise<GetAuditLogForTableResult[]>;
  getDashboardStats(): Promise<GetDashboardStatsResult | null>;
  getTopCommenters(limit: number): Promise<GetTopCommentersResult[]>;
  getEngagementTimeSeries(created_at_start: Date): Promise<GetEngagementTimeSeriesResult[]>;
  createCategory(name: string): Promise<Categories | null>;
  createPost(args: CreatePostParams): Promise<Posts | null>;
  createComment(args: CreateCommentParams): Promise<Comments | null>;
  deleteOldUsers(created_at: Date): Promise<number>;
  updateUserTimestamp(updated_at: Date, id: number): Promise<number>;
  createNotification(args: CreateNotificationParams): Promise<Notifications | null>;
  getNotificationsByUser(args: GetNotificationsByUserParams): Promise<Notifications[]>;
  getUnreadCount(user_id: number): Promise<number | null>;
  markNotificationRead(id: number, user_id: number): Promise<number>;
  markAllNotificationsRead(user_id: number): Promise<number>;
  deleteOldNotifications(user_id: number, created_at: Date): Promise<number>;
  getNotificationsByType(args: GetNotificationsByTypeParams): Promise<GetNotificationsByTypeResult[]>;
  createTag(args: CreateTagParams): Promise<Tags | null>;
  getTagBySlug(slug: string): Promise<Tags | null>;
  getAllTags(): Promise<Tags[]>;
  addTagToPost(post_id: number, tag_id: number): Promise<number>;
  removeTagFromPost(post_id: number, tag_id: number): Promise<number>;
  getTagsForPost(post_id: number): Promise<GetTagsForPostResult[]>;
  getPostsByTag(args: GetPostsByTagParams): Promise<GetPostsByTagResult[]>;
  getTopTags(limit: number): Promise<GetTopTagsResult[]>;
  uploadMedia(args: UploadMediaParams): Promise<Media | null>;
  getMediaByPost(post_id: number): Promise<GetMediaByPostResult[]>;
  getMediaByUser(args: GetMediaByUserParams): Promise<GetMediaByUserResult[]>;
  getMediaByType(user_id: number, type: string): Promise<GetMediaByTypeResult[]>;
  deleteMedia(id: string, user_id: number): Promise<number>;
  getStorageUsedByUser(user_id: number): Promise<GetStorageUsedByUserResult | null>;
  getLargeMediaFiles(size_bytes: number, limit: number): Promise<GetLargeMediaFilesResult[]>;
  getUserFeed(args: GetUserFeedParams): Promise<GetUserFeedResult[]>;
  searchPostsFullText(search_query: string, limit: number): Promise<SearchPostsFullTextResult[]>;
  bulkMarkNotificationsRead(user_id: number, id: number[]): Promise<number>;
  getUserWithStats(id: number): Promise<GetUserWithStatsResult | null>;
}

export function Newq(db: any): Queries;
