// Code generated by FlashORM. DO NOT EDIT.

class Queries {
  constructor(db) {
    this.db = db;
    this._stmts = new Map();
  }

  async getUserPrefs(id) {
    let stmt = this._stmts.get('getUserPrefs');
    if (!stmt) {
      stmt = `SELECT id, name, email, preferences FROM users WHERE id = $1;`;
      this._stmts.set('getUserPrefs', stmt);
    }
    const r = await this.db.query(stmt, [id]);
    return r.rows[0] || null;
  }

  async setUserPrefs(preferences, id) {
    let stmt = this._stmts.get('setUserPrefs');
    if (!stmt) {
      stmt = `UPDATE users SET preferences = $1, updated_at = NOW() WHERE id = $2 RETURNING id, name, preferences, updated_at;`;
      this._stmts.set('setUserPrefs', stmt);
    }
    const r = await this.db.query(stmt, [preferences, id]);
    return r.rows[0] || null;
  }

  async getPostMeta(id) {
    let stmt = this._stmts.get('getPostMeta');
    if (!stmt) {
      stmt = `SELECT id, title, status, metadata, user_id, created_at FROM posts WHERE id = $1;`;
      this._stmts.set('getPostMeta', stmt);
    }
    const r = await this.db.query(stmt, [id]);
    return r.rows[0] || null;
  }

  async listUsersWithPrefs(limit) {
    let stmt = this._stmts.get('listUsersWithPrefs');
    if (!stmt) {
      stmt = `SELECT id, name, email, preferences, created_at FROM users ORDER BY created_at DESC LIMIT $1;`;
      this._stmts.set('listUsersWithPrefs', stmt);
    }
    const r = await this.db.query(stmt, [limit]);
  }

  async listPostsWithMeta(user_id) {
    let stmt = this._stmts.get('listPostsWithMeta');
    if (!stmt) {
      stmt = `SELECT id, title, status, view_count, metadata, created_at FROM posts WHERE user_id = $1 AND status = 'published' ORDER BY created_at DESC;`;
      this._stmts.set('listPostsWithMeta', stmt);
    }
    const r = await this.db.query(stmt, [user_id]);
  }

}

module.exports = { Queries };
