// Code generated by FlashORM. DO NOT EDIT.

class Queries {
  constructor(db) {
    this.db = db;
    this._stmts = new Map();
  }

  async getusers() {
    let stmt = this._stmts.get('getusers');
    if (!stmt) {
      stmt = { name: 'getusers', text: `SELECT name FROM users;` };
      this._stmts.set('getusers', stmt);
    }
    const r = await this.db.query(stmt);
    return r.rows.map(row => row.name);
  }

}

module.exports = { Queries };
