// Code generated by FlashORM. DO NOT EDIT.

package kotlin

import org.jetbrains.exposed.sql.Database

class Queries(private val db: Database) {
    companion object {
        fun newq(db: Database): Queries = Queries(db)
    }
}
