// Code generated by FlashORM. DO NOT EDIT.

package kotlin

import java.util.UUID
import java.time.LocalDateTime
import java.sql.Connection

/**
 * Unified query interface. Use `Queries.newq(conn)` to obtain an instance.
 */
class Queries(private val conn: Connection) {

    private val users = UsersQueries(conn)

    companion object {
        fun newq(conn: Connection): Queries = Queries(conn)
    }

    fun createUser(name: String, email: String): Users? =
        users.createUser(name, email)

    fun createUserFull(args: CreateUserFullParams): Users? =
        users.createUserFull(args)

    fun getUser(id: Int): Users? =
        users.getUser(id)

    fun getUserByEmail(email: String): Users? =
        users.getUserByEmail(email)

    fun updateUserName(name: String, id: Int): Users? =
        users.updateUserName(name, id)

    fun updateUserRole(role: UserRole, id: Int): Unit =
        users.updateUserRole(role, id)

    fun deleteUser(id: Int): Unit =
        users.deleteUser(id)

    fun listUsers(limit: Int, offset: Int): List<Users> =
        users.listUsers(limit, offset)

    fun upsertUser(args: UpsertUserParams): Users? =
        users.upsertUser(args)

    fun upsertUserWithCOALESCE(args: UpsertUserWithCOALESCEParams): Users? =
        users.upsertUserWithCOALESCE(args)

    fun getUsersWithNullAddress(): List<GetUsersWithNullAddressRow> =
        users.getUsersWithNullAddress()

    fun getUsersWithBio(): List<GetUsersWithBioRow> =
        users.getUsersWithBio()

    fun getUserDisplayInfo(id: Int): GetUserDisplayInfoRow? =
        users.getUserDisplayInfo(id)

    fun searchUsersWithCOALESCE(args: SearchUsersWithCOALESCEParams): List<SearchUsersWithCOALESCERow> =
        users.searchUsersWithCOALESCE(args)

    fun getUsersCreatedBetween(created_at: LocalDateTime, created_at2: LocalDateTime): List<GetUsersCreatedBetweenRow> =
        users.getUsersCreatedBetween(created_at, created_at2)

    fun getUsersByAgeRange(age: Int, age2: Int): List<GetUsersByAgeRangeRow> =
        users.getUsersByAgeRange(age, age2)

    fun getUsersByGeneratedRange(age_range: Int): List<GetUsersByGeneratedRangeRow> =
        users.getUsersByGeneratedRange(age_range)

    fun getRecentUsers(args: GetRecentUsersParams): List<Users> =
        users.getRecentUsers(args)

    fun getUserPreferences(id: Int): GetUserPreferencesRow? =
        users.getUserPreferences(id)

    fun updateUserPreferences(preferences: String, id: Int): Unit =
        users.updateUserPreferences(preferences, id)

    fun findUsersByJsonKey(preferences: String): List<FindUsersByJsonKeyRow> =
        users.findUsersByJsonKey(preferences)

    fun findUsersByJsonContains(preferences: String): List<FindUsersByJsonContainsRow> =
        users.findUsersByJsonContains(preferences)

    fun getUsersWithTag(tags: List<String>): List<GetUsersWithTagRow> =
        users.getUsersWithTag(tags)

    fun getUsersWithAnyTag(tags: List<String>): List<GetUsersWithAnyTagRow> =
        users.getUsersWithAnyTag(tags)

    fun addUserTag(tags: List<String>, id: Int): Unit =
        users.addUserTag(tags, id)

    fun removeUserTag(tags: List<String>, id: Int): Unit =
        users.removeUserTag(tags, id)

    fun getUserShippingAddress(id: Int): GetUserShippingAddressRow? =
        users.getUserShippingAddress(id)

    fun updateUserShipping(args: UpdateUserShippingParams): Unit =
        users.updateUserShipping(args)

    fun getComplexUserAnalytics(args: GetComplexUserAnalyticsParams): List<GetComplexUserAnalyticsRow> =
        users.getComplexUserAnalytics(args)

    fun getPostWithActiveCommenters(rn: String, post_id: Int): List<GetPostWithActiveCommentersRow> =
        users.getPostWithActiveCommenters(rn, post_id)

    fun getUserPostRankings(limit: Int): List<GetUserPostRankingsRow> =
        users.getUserPostRankings(limit)

    fun getUserTrendingPosts(user_id: Int, limit: Int): List<GetUserTrendingPostsRow> =
        users.getUserTrendingPosts(user_id, limit)

    fun getPostCountByUser(user_id: Int): GetPostCountByUserRow? =
        users.getPostCountByUser(user_id)

    fun getUsersWithManyPosts(min_count: Int): List<GetUsersWithManyPostsRow> =
        users.getUsersWithManyPosts(min_count)

    fun getPostsWithCommentCount(limit: Int, offset: Int): List<GetPostsWithCommentCountRow> =
        users.getPostsWithCommentCount(limit, offset)

    fun getUsersWithActivityLevel(): List<GetUsersWithActivityLevelRow> =
        users.getUsersWithActivityLevel()

    fun getPostWithComments(id: Int): List<GetPostWithCommentsRow> =
        users.getPostWithComments(id)

    fun getPostDetailsWithAllRelations(id: Int): GetPostDetailsWithAllRelationsRow? =
        users.getPostDetailsWithAllRelations(id)

    fun countUsersByRole(role: UserRole): Int? =
        users.countUsersByRole(role)

    fun countUsers(): CountUsersRow? =
        users.countUsers()

    fun getUserRoleCount(): List<GetUserRoleCountRow> =
        users.getUserRoleCount()

    fun getUserAgeStats(): GetUserAgeStatsRow? =
        users.getUserAgeStats()

    fun getPostsGroupedByStatus(count_threshold: Int): List<GetPostsGroupedByStatusRow> =
        users.getPostsGroupedByStatus(count_threshold)

    fun getDistinctCommenters(): List<GetDistinctCommentersRow> =
        users.getDistinctCommenters()

    fun getLatestPostPerUser(): List<GetLatestPostPerUserRow> =
        users.getLatestPostPerUser()

    fun searchUsers(args: SearchUsersParams): List<SearchUsersRow> =
        users.searchUsers(args)

    fun searchPostsByTitle(args: SearchPostsByTitleParams): List<SearchPostsByTitleRow> =
        users.searchPostsByTitle(args)

    fun fullTextSearchPosts(search_query: String, limit: Int): List<FullTextSearchPostsRow> =
        users.fullTextSearchPosts(search_query, limit)

    fun getUserRegistrationStats(): List<GetUserRegistrationStatsRow> =
        users.getUserRegistrationStats()

    fun getWeeklyPostStats(created_at: LocalDateTime): List<GetWeeklyPostStatsRow> =
        users.getWeeklyPostStats(created_at)

    fun getUsersInIds(id: Int): List<Users> =
        users.getUsersInIds(id)

    fun getUsersByNames(name: String): List<GetUsersByNamesRow> =
        users.getUsersByNames(name)

    fun getUsersWhoCommented(): List<GetUsersWhoCommentedRow> =
        users.getUsersWhoCommented()

    fun getUsersWithNoPosts(): List<GetUsersWithNoPostsRow> =
        users.getUsersWithNoPosts()

    fun getAllContentByUser(user_id: Int, limit: Int): List<GetAllContentByUserRow> =
        users.getAllContentByUser(user_id, limit)

    fun getActiveUsers(limit: Int): List<ActiveUsers> =
        users.getActiveUsers(limit)

    fun getUserActivitySummary(post_count: Int, comment_count: Int): List<UserActivitySummary> =
        users.getUserActivitySummary(post_count, comment_count)

    fun refreshPostStats(): Unit =
        users.refreshPostStats()

    fun getPostStats(limit: Int): List<PostStats> =
        users.getPostStats(limit)

    fun getUserSubscriptions(user_id: Int): List<GetUserSubscriptionsRow> =
        users.getUserSubscriptions(user_id)

    fun createSubscription(args: CreateSubscriptionParams): Subscriptions? =
        users.createSubscription(args)

    fun getOrdersByUser(user_id: Int, limit: Int): List<GetOrdersByUserRow> =
        users.getOrdersByUser(user_id, limit)

    fun getOrdersInState(state: OrderState, limit: Int): List<GetOrdersInStateRow> =
        users.getOrdersInState(state, limit)

    fun getAuditLogForUser(args: GetAuditLogForUserParams): List<GetAuditLogForUserRow> =
        users.getAuditLogForUser(args)

    fun getAuditLogForTable(table_name: String, limit: Int): List<GetAuditLogForTableRow> =
        users.getAuditLogForTable(table_name, limit)

    fun getDashboardStats(): GetDashboardStatsRow? =
        users.getDashboardStats()

    fun getTopCommenters(limit: Int): List<GetTopCommentersRow> =
        users.getTopCommenters(limit)

    fun getEngagementTimeSeries(created_at: LocalDateTime): List<GetEngagementTimeSeriesRow> =
        users.getEngagementTimeSeries(created_at)

    fun createCategory(name: String): Categories? =
        users.createCategory(name)

    fun createPost(args: CreatePostParams): Posts? =
        users.createPost(args)

    fun createComment(args: CreateCommentParams): Comments? =
        users.createComment(args)

    fun deleteOldUsers(created_at: LocalDateTime): Unit =
        users.deleteOldUsers(created_at)

    fun updateUserTimestamp(updated_at: LocalDateTime, id: Int): Unit =
        users.updateUserTimestamp(updated_at, id)

    fun createNotification(args: CreateNotificationParams): Notifications? =
        users.createNotification(args)

    fun getNotificationsByUser(args: GetNotificationsByUserParams): List<Notifications> =
        users.getNotificationsByUser(args)

    fun getUnreadCount(user_id: Int): Int? =
        users.getUnreadCount(user_id)

    fun markNotificationRead(id: Int, user_id: Int): Unit =
        users.markNotificationRead(id, user_id)

    fun markAllNotificationsRead(user_id: Int): Unit =
        users.markAllNotificationsRead(user_id)

    fun deleteOldNotifications(user_id: Int, created_at: LocalDateTime): Unit =
        users.deleteOldNotifications(user_id, created_at)

    fun getNotificationsByType(args: GetNotificationsByTypeParams): List<GetNotificationsByTypeRow> =
        users.getNotificationsByType(args)

    fun createTag(args: CreateTagParams): Tags? =
        users.createTag(args)

    fun getTagBySlug(slug: String): Tags? =
        users.getTagBySlug(slug)

    fun getAllTags(): List<Tags> =
        users.getAllTags()

    fun addTagToPost(post_id: Int, tag_id: Int): Unit =
        users.addTagToPost(post_id, tag_id)

    fun removeTagFromPost(post_id: Int, tag_id: Int): Unit =
        users.removeTagFromPost(post_id, tag_id)

    fun getTagsForPost(post_id: Int): List<Tags> =
        users.getTagsForPost(post_id)

    fun getPostsByTag(args: GetPostsByTagParams): List<GetPostsByTagRow> =
        users.getPostsByTag(args)

    fun getTopTags(limit: Int): List<GetTopTagsRow> =
        users.getTopTags(limit)

    fun uploadMedia(args: UploadMediaParams): Media? =
        users.uploadMedia(args)

    fun getMediaByPost(post_id: Int): List<GetMediaByPostRow> =
        users.getMediaByPost(post_id)

    fun getMediaByUser(args: GetMediaByUserParams): List<GetMediaByUserRow> =
        users.getMediaByUser(args)

    fun getMediaByType(user_id: Int, type: String): List<GetMediaByTypeRow> =
        users.getMediaByType(user_id, type)

    fun deleteMedia(id: UUID, user_id: Int): Unit =
        users.deleteMedia(id, user_id)

    fun getStorageUsedByUser(user_id: Int): GetStorageUsedByUserRow? =
        users.getStorageUsedByUser(user_id)

    fun getLargeMediaFiles(size_bytes: Long, limit: Int): List<GetLargeMediaFilesRow> =
        users.getLargeMediaFiles(size_bytes, limit)

    fun getUserFeed(args: GetUserFeedParams): List<GetUserFeedRow> =
        users.getUserFeed(args)

    fun searchPostsFullText(search_query: String, limit: Int): List<SearchPostsFullTextRow> =
        users.searchPostsFullText(search_query, limit)

    fun bulkMarkNotificationsRead(user_id: Int, id: Int): Unit =
        users.bulkMarkNotificationsRead(user_id, id)

    fun getUserWithStats(id: Int): GetUserWithStatsRow? =
        users.getUserWithStats(id)

    fun close() {
        users.close()
    }
}
