package kotlingen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Lumos-Labs-HQ/flash/internal/config"
	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
	"github.com/Lumos-Labs-HQ/flash/internal/parser"
	"github.com/Lumos-Labs-HQ/flash/internal/utils"
)

type Generator struct {
	Config       *config.Config
	schema       *parser.Schema
	schemaParser *parser.SchemaParser
	queryParser  *parser.QueryParser
	cache        *gencommon.GenerationCache
}

func New(cfg *config.Config) *Generator {
	cache := gencommon.NewGenerationCache()
	cache.OutDir = cfg.Gen.Kotlin.Out
	return &Generator{
		Config:       cfg,
		schemaParser: parser.NewSchemaParser(cfg),
		queryParser:  parser.NewQueryParser(cfg),
		cache:        cache,
	}
}

func (g *Generator) Generate() error {
	if err := os.MkdirAll(g.Config.Gen.Kotlin.Out, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	schema, err := g.schemaParser.Parse()
	if err != nil {
		return fmt.Errorf("failed to parse schema: %w", err)
	}
	g.schema = schema

	schemaHash, _ := g.cache.ComputeSchemaChecksum(g.Config.SchemaDir)
	configHash := fmt.Sprintf("%x", []byte(fmt.Sprintf("%s|%s|%s", g.Config.Database.Provider, g.Config.Gen.Kotlin.Out, g.Config.Gen.Kotlin.Driver)))
	fullRegen := g.cache.ShouldRegenerateAll(schemaHash, configHash)

	queries, err := g.queryParser.Parse(schema)
	if err != nil {
		return fmt.Errorf("failed to parse queries: %w", err)
	}

	if fullRegen || g.cache.SchemaChecksum != schemaHash {
		if err := g.generateModels(); err != nil {
			return err
		}
		if err := g.generateDB(queries); err != nil {
			return err
		}
	}

	if err := g.generateQueriesIncremental(queries, fullRegen); err != nil {
		return err
	}

	g.cache.UpdateSchemaChecksum(schemaHash)
	g.cache.UpdateConfigChecksum(configHash)
	g.cache.MarkGeneration()
	_ = g.cache.Save()
	return nil
}

func (g *Generator) generateModels() error {
	var w strings.Builder
	w.Grow(200 + len(g.schema.Tables)*200)

	pkg := toKotlinPackage(&g.Config.Gen.Kotlin)
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString(fmt.Sprintf("package %s\n\n", pkg))

	needsUUID := false
	needsLocalDateTime := false
	for _, t := range g.schema.Tables {
		for _, c := range t.Columns {
			kt := g.sqlTypeToKotlin(c.Type, false)
			if strings.Contains(kt, "UUID") {
				needsUUID = true
			}
			if strings.Contains(kt, "LocalDateTime") {
				needsLocalDateTime = true
			}
		}
	}
	if needsUUID {
		w.WriteString("import java.util.UUID\n")
	}
	if needsLocalDateTime {
		w.WriteString("import java.time.LocalDateTime\n")
	}
	if needsUUID || needsLocalDateTime {
		w.WriteString("\n")
	}

	for _, enum := range g.schema.Enums {
		name := utils.ToPascalCase(enum.Name)
		w.WriteString(fmt.Sprintf("enum class %s {\n", name))
		for i, v := range enum.Values {
			if i < len(enum.Values)-1 {
				w.WriteString(fmt.Sprintf("    %s,\n", strings.ToUpper(v)))
			} else {
				w.WriteString(fmt.Sprintf("    %s\n", strings.ToUpper(v)))
			}
		}
		w.WriteString("}\n\n")
	}

	for _, table := range g.schema.Tables {
		name := utils.ToPascalCase(table.Name)
		w.WriteString(fmt.Sprintf("data class %s(\n", name))
		for i, col := range table.Columns {
			if col.Name == "*" {
				continue
			}
			kt := g.sqlTypeToKotlin(col.Type, col.Nullable)
			comma := ","
			if i == len(table.Columns)-1 {
				comma = ""
			}
			w.WriteString(fmt.Sprintf("    val %s: %s%s\n", utils.ToSnakeCase(col.Name), kt, comma))
		}
		w.WriteString(")\n\n")
	}

	return os.WriteFile(filepath.Join(g.Config.Gen.Kotlin.Out, "Models.kt"), []byte(w.String()), 0644)
}

func (g *Generator) generateDB(queries []*parser.Query) error {
	pkg := toKotlinPackage(&g.Config.Gen.Kotlin)
	driver := g.Config.Gen.Kotlin.Driver
	provider := g.Config.Database.Provider
	isScylla := provider == "scylla" || provider == "scylladb" || provider == "cassandra"

	// Collect unique source file base names
	seen := map[string]bool{}
	var files []string
	for _, q := range queries {
		src := q.SourceFile
		if src == "" {
			src = "queries"
		}
		base := strings.TrimSuffix(src, ".sql")
		if !seen[base] {
			seen[base] = true
			files = append(files, base)
		}
	}

	var connType, connParam, connImport string
	switch {
	case isScylla:
		connImport = "import com.datastax.oss.driver.api.core.CqlSession\n"
		connType = "CqlSession"
		connParam = "session"
	case driver == "exposed":
		connImport = "import org.jetbrains.exposed.sql.Database\n"
		connType = "Database"
		connParam = "db"
	case driver == "r2dbc":
		connImport = "import io.r2dbc.spi.Connection\n"
		connType = "Connection"
		connParam = "conn"
	default: // jdbc
		connImport = "import java.sql.Connection\n"
		connType = "Connection"
		connParam = "conn"
	}

	var w strings.Builder
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	w.WriteString(connImport + "\n")
	w.WriteString("/**\n * Unified query interface. Use `Queries.newq(conn)` to obtain an instance.\n */\n")
	w.WriteString("class Queries(private val " + connParam + ": " + connType + ") {\n\n")

	// Delegate fields — one per query file class
	for _, base := range files {
		className := utils.ToPascalCase(base) + "Queries"
		w.WriteString(fmt.Sprintf("    private val %s = %s(%s)\n", base, className, connParam))
	}
	w.WriteString("\n")

	// companion object with newq factory
	w.WriteString("    companion object {\n")
	w.WriteString(fmt.Sprintf("        fun newq(%s: %s): Queries = Queries(%s)\n", connParam, connType, connParam))
	w.WriteString("    }\n\n")

	// Proxy every query method
	for _, q := range queries {
		src := q.SourceFile
		if src == "" {
			src = "queries"
		}
		base := strings.TrimSuffix(src, ".sql")
		columns := g.expandWildcardColumns(q)
		cmd := strings.ToLower(q.Cmd)
		methodName := toCamelCase(q.Name)

		rowType := queryPascal(q.Name) + "Row"
		if mt := g.modelTypeForQuery(q, columns); mt != "" {
			rowType = mt
		}

		var retType string
		switch cmd {
		case ":one":
			if len(columns) == 1 {
				retType = g.sqlTypeToKotlin(columns[0].Type, true)
			} else if len(columns) > 1 {
				retType = rowType + "?"
			} else {
				retType = "Unit"
			}
		case ":many":
			if len(columns) == 1 {
				retType = fmt.Sprintf("List<%s>", g.sqlTypeToKotlin(columns[0].Type, false))
			} else if len(columns) > 1 {
				retType = fmt.Sprintf("List<%s>", rowType)
			} else {
				retType = "List<Map<String, Any?>>"
			}
		case ":execresult":
			retType = "Long"
		default:
			retType = "Unit"
		}

		params := make([]string, len(q.Params))
		args := make([]string, len(q.Params))
		for i, p := range q.Params {
			params[i] = fmt.Sprintf("%s: %s", utils.ToSnakeCase(p.Name), g.sqlTypeToKotlin(p.Type, false))
			args[i] = utils.ToSnakeCase(p.Name)
		}

		retStmt := ""
		if retType != "Unit" {
			retStmt = "return "
		}
		w.WriteString(fmt.Sprintf("    fun %s(%s): %s =\n", methodName, strings.Join(params, ", "), retType))
		w.WriteString(fmt.Sprintf("        %s.%s(%s)\n\n", base, methodName, strings.Join(args, ", ")))
		_ = retStmt
	}

	// close for JDBC
	if !isScylla && driver != "exposed" && driver != "r2dbc" {
		w.WriteString("    fun close() {\n")
		for _, base := range files {
			w.WriteString(fmt.Sprintf("        %s.close()\n", base))
		}
		w.WriteString("    }\n")
	}
	w.WriteString("}\n")

	return os.WriteFile(filepath.Join(g.Config.Gen.Kotlin.Out, "Queries.kt"), []byte(w.String()), 0644)
}

// queryPascal returns the query name as PascalCase, preserving existing casing.
// Query names from SQL annotations are already PascalCase (e.g. "GetUserWithPostCount").
func queryPascal(name string) string {
	if name == "" {
		return name
	}
	// If it already starts uppercase, use as-is (already PascalCase)
	if name[0] >= 'A' && name[0] <= 'Z' {
		return name
	}
	return utils.ToPascalCase(name)
}
func toCamelCase(name string) string {
	if name == "" {
		return name
	}
	if name[0] >= 'A' && name[0] <= 'Z' {
		return strings.ToLower(name[:1]) + name[1:]
	}
	pascal := utils.ToPascalCase(name)
	if pascal == "" {
		return pascal
	}
	return strings.ToLower(pascal[:1]) + pascal[1:]
}

func (g *Generator) generateQueryMethod(w *strings.Builder, query *parser.Query) {
	methodName := toCamelCase(query.Name)
	columns := g.expandWildcardColumns(query)
	cmd := strings.ToLower(query.Cmd)
	driver := g.Config.Gen.Kotlin.Driver
	provider := g.Config.Database.Provider
	isScylla := provider == "scylla" || provider == "scylladb" || provider == "cassandra"

	// Row type
	rowType := queryPascal(query.Name) + "Row"
	if mt := g.modelTypeForQuery(query, columns); mt != "" {
		rowType = mt
	}

	// Build param list
	params := make([]string, len(query.Params))
	for i, p := range query.Params {
		params[i] = fmt.Sprintf("%s: %s", utils.ToSnakeCase(p.Name), g.sqlTypeToKotlin(p.Type, false))
	}

	// Return type
	var retType string
	switch cmd {
	case ":one":
		if len(columns) == 1 {
			retType = g.sqlTypeToKotlin(columns[0].Type, true)
		} else if len(columns) > 1 {
			retType = rowType + "?"
		} else {
			retType = "Unit"
		}
	case ":many":
		if len(columns) == 1 {
			retType = fmt.Sprintf("List<%s>", g.sqlTypeToKotlin(columns[0].Type, false))
		} else if len(columns) > 1 {
			retType = fmt.Sprintf("List<%s>", rowType)
		} else {
			retType = "List<Map<String, Any?>>"
		}
	case ":execresult":
		retType = "Long"
	default:
		retType = "Unit"
	}

	paramStr := strings.Join(params, ", ")
	w.WriteString(fmt.Sprintf("    fun %s(%s): %s {\n", methodName, paramStr, retType))

	// SQL constant
	sql := strings.TrimSpace(query.SQL)
	if isScylla || driver == "" || driver == "jdbc" || driver == "default" {
		// Convert PostgreSQL $N to ? for JDBC/CQL
		for i := 20; i >= 1; i-- {
			sql = strings.ReplaceAll(sql, fmt.Sprintf("$%d", i), "?")
		}
	}
	w.WriteString(fmt.Sprintf("        val sql = \"\"\"%s\"\"\"\n", sql))

	if isScylla {
		g.generateScyllaBody(w, query, columns, cmd, rowType)
	} else if driver == "r2dbc" {
		g.generateR2DBCBody(w, query, columns, cmd, rowType)
	} else if driver == "exposed" {
		g.generateExposedBody(w, query, columns, cmd, rowType)
	} else {
		g.generateJDBCBody(w, query, columns, cmd, rowType)
	}

	w.WriteString("    }\n\n")
}

// ktTypedGetter returns the typed Kotlin ResultSet getter by column name.
func ktTypedGetter(colName, sqlType string, nullable bool) string {
	sl := strings.ToLower(sqlType)
	switch {
	case strings.Contains(sl, "bigint") || sl == "int8" || sl == "uint64":
		return fmt.Sprintf("rs.getLong(\"%s\")", colName)
	case strings.Contains(sl, "int") || strings.Contains(sl, "serial") || sl == "uint8" || sl == "uint16" || sl == "uint32":
		return fmt.Sprintf("rs.getInt(\"%s\")", colName)
	case sl == "float32":
		return fmt.Sprintf("rs.getFloat(\"%s\")", colName)
	case sl == "float64" || strings.Contains(sl, "double") || strings.Contains(sl, "numeric") || strings.Contains(sl, "decimal"):
		return fmt.Sprintf("rs.getDouble(\"%s\")", colName)
	case strings.Contains(sl, "bool"):
		return fmt.Sprintf("rs.getBoolean(\"%s\")", colName)
	case sl == "timeuuid" || strings.Contains(sl, "uuid"):
		return fmt.Sprintf("rs.getObject(\"%s\", java.util.UUID::class.java)", colName)
	case strings.Contains(sl, "timestamp") || strings.Contains(sl, "date") || strings.Contains(sl, "time"):
		if nullable {
			return fmt.Sprintf("rs.getTimestamp(\"%s\")?.toLocalDateTime()", colName)
		}
		return fmt.Sprintf("rs.getTimestamp(\"%s\")!!.toLocalDateTime()", colName)
	case sl == "bytea" || strings.Contains(sl, "blob"):
		return fmt.Sprintf("rs.getBytes(\"%s\")", colName)
	case strings.HasSuffix(sl, "[]") || strings.HasPrefix(sl, "set<") || strings.HasPrefix(sl, "list<"):
		return fmt.Sprintf("rs.getArray(\"%s\")?.array as? Array<*>", colName)
	case strings.Contains(sl, "json"):
		return fmt.Sprintf("rs.getString(\"%s\")", colName)
	default:
		return fmt.Sprintf("rs.getString(\"%s\")", colName)
	}
}

// ktTypedSetter returns a typed Kotlin PreparedStatement setter.
func ktTypedSetter(idx int, paramName, sqlType string) string {
	sl := strings.ToLower(sqlType)
	switch {
	case strings.Contains(sl, "bigint") || sl == "int8" || sl == "uint64":
		return fmt.Sprintf("stmt.setLong(%d, %s)", idx, paramName)
	case strings.Contains(sl, "int") || strings.Contains(sl, "serial") || sl == "uint8" || sl == "uint16" || sl == "uint32":
		return fmt.Sprintf("stmt.setInt(%d, %s)", idx, paramName)
	case sl == "float32":
		return fmt.Sprintf("stmt.setFloat(%d, %s)", idx, paramName)
	case sl == "float64" || strings.Contains(sl, "double") || strings.Contains(sl, "numeric") || strings.Contains(sl, "decimal"):
		return fmt.Sprintf("stmt.setDouble(%d, %s)", idx, paramName)
	case strings.Contains(sl, "bool"):
		return fmt.Sprintf("stmt.setBoolean(%d, %s)", idx, paramName)
	case sl == "bytea" || strings.Contains(sl, "blob"):
		return fmt.Sprintf("stmt.setBytes(%d, %s)", idx, paramName)
	case strings.Contains(sl, "uuid") || sl == "timeuuid":
		return fmt.Sprintf("stmt.setObject(%d, %s)", idx, paramName)
	case strings.Contains(sl, "timestamp") || strings.Contains(sl, "date") || strings.Contains(sl, "time"):
		return fmt.Sprintf("stmt.setObject(%d, java.sql.Timestamp.valueOf(%s))", idx, paramName)
	case strings.Contains(sl, "varchar") || strings.Contains(sl, "text") || strings.Contains(sl, "char"):
		return fmt.Sprintf("stmt.setString(%d, %s)", idx, paramName)
	default:
		// enums, json, arrays — setObject handles all; no .toString() needed
		return fmt.Sprintf("stmt.setObject(%d, %s)", idx, paramName)
	}
}

// cqlKtGetter returns DataStax typed getter by column name for Kotlin.
func cqlKtGetter(colName, sqlType string) string {
	sl := strings.ToLower(sqlType)
	switch {
	case sl == "uuid" || sl == "timeuuid":
		return fmt.Sprintf("row.getUuid(\"%s\")", colName)
	case strings.Contains(sl, "bigint") || sl == "int8" || sl == "varint" || sl == "counter":
		return fmt.Sprintf("row.getLong(\"%s\")", colName)
	case strings.Contains(sl, "int"):
		return fmt.Sprintf("row.getInt(\"%s\")", colName)
	case sl == "float32":
		return fmt.Sprintf("row.getFloat(\"%s\")", colName)
	case sl == "float64" || strings.Contains(sl, "double") || strings.Contains(sl, "decimal"):
		return fmt.Sprintf("row.getDouble(\"%s\")", colName)
	case strings.Contains(sl, "bool"):
		return fmt.Sprintf("row.getBoolean(\"%s\")", colName)
	case strings.Contains(sl, "timestamp") || strings.Contains(sl, "date") || strings.Contains(sl, "time"):
		return fmt.Sprintf("row.getInstant(\"%s\")", colName)
	case strings.HasPrefix(sl, "set<"):
		inner, _ := parseCQLInner(sl)
		return fmt.Sprintf("row.getSet(\"%s\", %s::class.java)", colName, cqlInnerKtClass(inner))
	case strings.HasPrefix(sl, "list<"):
		inner, _ := parseCQLInner(sl)
		return fmt.Sprintf("row.getList(\"%s\", %s::class.java)", colName, cqlInnerKtClass(inner))
	case strings.HasPrefix(sl, "map<"):
		k, v := parseCQLInner(sl)
		return fmt.Sprintf("row.getMap(\"%s\", %s::class.java, %s::class.java)", colName, cqlInnerKtClass(k), cqlInnerKtClass(v))
	default:
		return fmt.Sprintf("row.getString(\"%s\")", colName)
	}
}

// parseCQLInner extracts inner type(s) from CQL collection wrappers.
func parseCQLInner(sl string) (string, string) {
	for _, prefix := range []string{"set<", "list<", "frozen<"} {
		if strings.HasPrefix(sl, prefix) && strings.HasSuffix(sl, ">") {
			return strings.TrimSpace(sl[len(prefix) : len(sl)-1]), ""
		}
	}
	if strings.HasPrefix(sl, "map<") && strings.HasSuffix(sl, ">") {
		inner := sl[4 : len(sl)-1]
		depth := 0
		for i, ch := range inner {
			switch ch {
			case '<':
				depth++
			case '>':
				depth--
			case ',':
				if depth == 0 {
					return strings.TrimSpace(inner[:i]), strings.TrimSpace(inner[i+1:])
				}
			}
		}
	}
	return "text", ""
}

// cqlInnerKtClass maps a CQL element type to its Kotlin class reference.
func cqlInnerKtClass(t string) string {
	switch strings.ToLower(strings.TrimSpace(t)) {
	case "uuid", "timeuuid":
		return "java.util.UUID"
	case "bigint", "counter", "varint", "int8":
		return "Long"
	case "int":
		return "Int"
	case "float":
		return "Float"
	case "double", "decimal":
		return "Double"
	case "boolean":
		return "Boolean"
	case "timestamp", "date", "time":
		return "java.time.Instant"
	default:
		return "String"
	}
}

func (g *Generator) generateJDBCBody(w *strings.Builder, query *parser.Query, columns []*parser.QueryColumn, cmd, rowType string) {
	methodName := toCamelCase(query.Name)
	key := fmt.Sprintf("\"%s\"", methodName)

	w.WriteString(fmt.Sprintf("        val stmt = stmts.getOrPut(%s) { conn.prepareStatement(sql) }\n", key))

	for i, p := range query.Params {
		w.WriteString(fmt.Sprintf("        %s\n", ktTypedSetter(i+1, utils.ToSnakeCase(p.Name), p.Type)))
	}

	switch cmd {
	case ":one":
		w.WriteString("        stmt.executeQuery().use { rs ->\n")
		if len(columns) == 0 {
			w.WriteString("            return\n")
		} else if len(columns) == 1 {
			w.WriteString(fmt.Sprintf("            return if (rs.next()) %s else null\n", ktTypedGetter(columns[0].Name, columns[0].Type, columns[0].Nullable)))
		} else {
			w.WriteString(fmt.Sprintf("            return if (rs.next()) %s(\n", rowType))
			for i, col := range columns {
				comma := ","
				if i == len(columns)-1 {
					comma = ""
				}
				w.WriteString(fmt.Sprintf("                %s%s\n", ktTypedGetter(col.Name, col.Type, col.Nullable), comma))
			}
			w.WriteString("            ) else null\n")
		}
		w.WriteString("        }\n")
	case ":many":
		w.WriteString(fmt.Sprintf("        val items = mutableListOf<%s>()\n", func() string {
			if len(columns) == 1 {
				return g.sqlTypeToKotlin(columns[0].Type, false)
			}
			return rowType
		}()))
		w.WriteString("        stmt.executeQuery().use { rs ->\n")
		if len(columns) == 1 {
			w.WriteString(fmt.Sprintf("            while (rs.next()) items.add(%s)\n", ktTypedGetter(columns[0].Name, columns[0].Type, columns[0].Nullable)))
		} else if len(columns) > 1 {
			w.WriteString("            while (rs.next()) items.add(\n")
			w.WriteString(fmt.Sprintf("                %s(\n", rowType))
			for i, col := range columns {
				comma := ","
				if i == len(columns)-1 {
					comma = ""
				}
				w.WriteString(fmt.Sprintf("                    %s%s\n", ktTypedGetter(col.Name, col.Type, col.Nullable), comma))
			}
			w.WriteString("                )\n            )\n")
		}
		w.WriteString("        }\n")
		w.WriteString("        return items\n")
	case ":execresult":
		w.WriteString("        stmt.executeUpdate()\n")
		w.WriteString("        return stmt.generatedKeys?.use { if (it.next()) it.getLong(1) else 0L } ?: 0L\n")
	default:
		w.WriteString("        stmt.executeUpdate()\n")
	}
}

func (g *Generator) generateScyllaBody(w *strings.Builder, query *parser.Query, columns []*parser.QueryColumn, cmd, rowType string) {
	args := make([]string, len(query.Params))
	for i, p := range query.Params {
		args[i] = utils.ToSnakeCase(p.Name)
	}

	execLine := "        session.execute(sql)\n"
	rsLine := "        val rs = session.execute(sql)\n"
	if len(args) > 0 {
		argsStr := strings.Join(args, ", ")
		execLine = fmt.Sprintf("        session.execute(com.datastax.oss.driver.api.core.cql.SimpleStatement.newInstance(sql, %s))\n", argsStr)
		rsLine = fmt.Sprintf("        val rs = session.execute(com.datastax.oss.driver.api.core.cql.SimpleStatement.newInstance(sql, %s))\n", argsStr)
	}

	switch cmd {
	case ":exec", ":execresult":
		w.WriteString(execLine)
	case ":one":
		w.WriteString(rsLine)
		w.WriteString("        val row = rs.one() ?: return null\n")
		if len(columns) == 1 {
			w.WriteString(fmt.Sprintf("        return %s\n", cqlKtGetter(columns[0].Name, columns[0].Type)))
		} else if len(columns) > 1 {
			w.WriteString(fmt.Sprintf("        return %s(\n", rowType))
			for i, col := range columns {
				comma := ","
				if i == len(columns)-1 {
					comma = ""
				}
				w.WriteString(fmt.Sprintf("            %s%s\n", cqlKtGetter(col.Name, col.Type), comma))
			}
			w.WriteString("        )\n")
		}
	case ":many":
		w.WriteString(rsLine)
		if len(columns) == 1 {
			kt := g.sqlTypeToKotlin(columns[0].Type, false)
			w.WriteString(fmt.Sprintf("        val items = mutableListOf<%s>()\n", kt))
			w.WriteString(fmt.Sprintf("        for (row in rs) items.add(%s)\n", cqlKtGetter(columns[0].Name, columns[0].Type)))
			w.WriteString("        return items\n")
		} else if len(columns) > 1 {
			w.WriteString(fmt.Sprintf("        return rs.map { row -> %s(\n", rowType))
			for i, col := range columns {
				comma := ","
				if i == len(columns)-1 {
					comma = ""
				}
				w.WriteString(fmt.Sprintf("            %s%s\n", cqlKtGetter(col.Name, col.Type), comma))
			}
			w.WriteString("        ) }.toList()\n")
		} else {
			w.WriteString("        return emptyList()\n")
		}
	}
}

func (g *Generator) generateR2DBCBody(w *strings.Builder, query *parser.Query, columns []*parser.QueryColumn, cmd, rowType string) {
	w.WriteString("        // R2DBC: use reactive execute, this is a blocking stub\n")
	w.WriteString("        val stmt = conn.createStatement(sql)\n")
	for i, p := range query.Params {
		w.WriteString(fmt.Sprintf("        stmt.bind(%d, %s)\n", i, utils.ToSnakeCase(p.Name)))
	}
	w.WriteString("        // TODO: subscribe to stmt.execute() with your reactor/coroutine bridge\n")
	if cmd == ":one" || cmd == ":many" {
		w.WriteString(fmt.Sprintf("        return null // replace with reactive mapping to %s\n", rowType))
	}
}

func (g *Generator) generateExposedBody(w *strings.Builder, query *parser.Query, columns []*parser.QueryColumn, cmd, rowType string) {
	w.WriteString("        // Exposed: wrap in transaction { ... }\n")
	w.WriteString("        return org.jetbrains.exposed.sql.transactions.transaction(db) {\n")
	if len(query.Params) > 0 {
		args := make([]string, len(query.Params))
		for i, p := range query.Params {
			args[i] = utils.ToSnakeCase(p.Name)
		}
		w.WriteString(fmt.Sprintf("            exec(sql, args = listOf(%s)) { rs ->\n", strings.Join(args, ", ")))
	} else {
		w.WriteString("            exec(sql) { rs ->\n")
	}
	if cmd == ":one" && len(columns) > 1 {
		w.WriteString(fmt.Sprintf("                if (rs.next()) %s(\n", rowType))
		for i, col := range columns {
			comma := ","
			if i == len(columns)-1 {
				comma = ""
			}
			w.WriteString(fmt.Sprintf("                    rs.getObject(%d) as %s%s\n", i+1, g.sqlTypeToKotlin(col.Type, col.Nullable), comma))
		}
		w.WriteString("                ) else null\n")
	} else {
		w.WriteString("                rs.next()\n")
	}
	w.WriteString("            }\n")
	w.WriteString("        }\n")
}

// cqlInnerKtType maps a CQL element type to its Kotlin type name (for generics).
func cqlInnerKtType(t string) string {
	switch strings.ToLower(strings.TrimSpace(t)) {
	case "uuid", "timeuuid":
		return "java.util.UUID"
	case "bigint", "counter", "varint", "int8":
		return "Long"
	case "int":
		return "Int"
	case "float":
		return "Float"
	case "double", "decimal":
		return "Double"
	case "boolean":
		return "Boolean"
	case "timestamp", "date", "time":
		return "java.time.Instant"
	default:
		return "String"
	}
}

// nullable_ appends "?" to a Kotlin type when nullable.
func nullable_(t string, nullable bool) string {
	if nullable {
		return t + "?"
	}
	return t
}

func (g *Generator) sqlTypeToKotlin(sqlType string, nullable bool) string {
	sqlLower := strings.ToLower(sqlType)

	if g.schema != nil {
		for _, enum := range g.schema.Enums {
			if strings.ToLower(enum.Name) == sqlLower {
				t := utils.ToPascalCase(enum.Name)
				if nullable {
					return t + "?"
				}
				return t
			}
		}
	}

	var kt string
	switch {
	// CQL collections — must be before contains("int") / contains("map")
	case strings.HasPrefix(sqlLower, "set<"):
		inner, _ := parseCQLInner(sqlLower)
		return nullable_(fmt.Sprintf("Set<%s>", cqlInnerKtType(inner)), nullable)
	case strings.HasPrefix(sqlLower, "list<"):
		inner, _ := parseCQLInner(sqlLower)
		return nullable_(fmt.Sprintf("List<%s>", cqlInnerKtType(inner)), nullable)
	case strings.HasPrefix(sqlLower, "map<"):
		k, v := parseCQLInner(sqlLower)
		return nullable_(fmt.Sprintf("Map<%s, %s>", cqlInnerKtType(k), cqlInnerKtType(v)), nullable)
	case strings.HasPrefix(sqlLower, "frozen<"), strings.HasPrefix(sqlLower, "tuple<"):
		kt = "String"
	// ClickHouse exact unsigned — before contains("int")
	case sqlLower == "uint8" || sqlLower == "uint16" || sqlLower == "uint32" || sqlLower == "uint64":
		kt = "Long"
	// ClickHouse exact float — before contains("float")
	case sqlLower == "float32":
		kt = "Float"
	case sqlLower == "float64":
		kt = "Double"
	case sqlLower == "string" || strings.HasPrefix(sqlLower, "fixedstring"):
		kt = "String"
	// timeuuid is a UUID variant — must be before contains("time")
	case sqlLower == "timeuuid":
		kt = "UUID"
	// Generic SQL types
	case strings.Contains(sqlLower, "bigint") || sqlLower == "int8":
		kt = "Long"
	case strings.Contains(sqlLower, "int") || strings.Contains(sqlLower, "serial"):
		kt = "Int"
	case strings.Contains(sqlLower, "float"):
		kt = "Float"
	case strings.Contains(sqlLower, "double") || strings.Contains(sqlLower, "numeric") || strings.Contains(sqlLower, "decimal"):
		kt = "Double"
	case strings.Contains(sqlLower, "bool"):
		kt = "Boolean"
	case strings.Contains(sqlLower, "timestamp") || strings.Contains(sqlLower, "date") || strings.Contains(sqlLower, "time"):
		kt = "LocalDateTime"
	case strings.Contains(sqlLower, "uuid"):
		kt = "UUID"
	case strings.Contains(sqlLower, "json"):
		kt = "String" // raw JSON string
	case sqlLower == "bytea" || strings.Contains(sqlLower, "blob"):
		kt = "ByteArray"
	case strings.HasSuffix(sqlLower, "[]"):
		inner := g.sqlTypeToKotlin(strings.TrimSuffix(sqlLower, "[]"), false)
		kt = fmt.Sprintf("List<%s>", inner)
	default:
		kt = "String"
	}
	if nullable {
		return kt + "?"
	}
	return kt
}

func (g *Generator) expandWildcardColumns(query *parser.Query) []*parser.QueryColumn {
	if len(query.Columns) > 1 {
		return query.Columns
	}
	if len(query.Columns) == 1 && query.Columns[0].Name != "*" {
		return query.Columns
	}
	tableName := utils.ExtractTableName(query.SQL)
	if tableName == "" || g.schema == nil {
		return query.Columns
	}
	for _, t := range g.schema.Tables {
		if strings.EqualFold(t.Name, tableName) {
			expanded := make([]*parser.QueryColumn, 0, len(t.Columns))
			for _, col := range t.Columns {
				expanded = append(expanded, &parser.QueryColumn{Name: col.Name, Type: col.Type, Table: t.Name, Nullable: col.Nullable})
			}
			return expanded
		}
	}
	return query.Columns
}

func (g *Generator) modelTypeForQuery(query *parser.Query, columns []*parser.QueryColumn) string {
	if len(columns) == 0 || g.schema == nil {
		return ""
	}
	tableName := utils.ExtractTableName(query.SQL)
	if tableName == "" {
		return ""
	}
	for _, t := range g.schema.Tables {
		if !strings.EqualFold(t.Name, tableName) || len(t.Columns) != len(columns) {
			continue
		}
		match := true
		for i, col := range columns {
			if !strings.EqualFold(col.Name, t.Columns[i].Name) {
				match = false
				break
			}
		}
		if match {
			return utils.ToPascalCase(tableName)
		}
	}
	return ""
}

// toKotlinPackage returns the package name: config value takes priority over dir name.
func toKotlinPackage(cfg *config.KotlinGen) string {
	if cfg.Package != "" {
		return cfg.Package
	}
	base := filepath.Base(cfg.Out)
	return strings.ReplaceAll(strings.ToLower(base), "-", "_")
}
