package kotlingen

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
)

func (g *Generator) generateMigrations() error {
	migrations, err := gencommon.LoadEmbeddedMigrations(g.Config.MigrationsPath)
	if err != nil {
		return err
	}
	pkg := toKotlinPackage(&g.Config.Gen.Kotlin)
	var w strings.Builder
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\npackage " + pkg + "\n\nimport java.sql.Connection\n\nobject FlashMigrations {\n")
	w.WriteString("  private data class Migration(val id: String, val name: String, val checksum: String, val statements: List<String>)\n  private val migrations = listOf(\n")
	for i, m := range migrations {
		comma := ","
		if i == len(migrations)-1 {
			comma = ""
		}
		w.WriteString(fmt.Sprintf("    Migration(%s, %s, %s, listOf(", strconv.Quote(m.ID), strconv.Quote(m.Name), strconv.Quote(m.Checksum)))
		for j, s := range m.Statements {
			if j > 0 {
				w.WriteString(", ")
			}
			w.WriteString(strconv.Quote(s))
		}
		w.WriteString("))" + comma + "\n")
	}
	w.WriteString("  )\n\n  /** Applies embedded migrations without invoking the Flash binary. */\n  fun FlashInitMigrate(conn: Connection) {\n    conn.createStatement().use { it.execute(\"CREATE TABLE IF NOT EXISTS _flash_migrations (id VARCHAR(255) PRIMARY KEY, checksum VARCHAR(64) NOT NULL, finished_at TIMESTAMP, migration_name VARCHAR(255) NOT NULL, started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)\") }\n    val known = mutableMapOf<String,String>()\n    conn.createStatement().use { st -> st.executeQuery(\"SELECT id, checksum FROM _flash_migrations WHERE finished_at IS NOT NULL\").use { rs -> while (rs.next()) known[rs.getString(1)] = rs.getString(2) } }\n    for (migration in migrations) { if (known.containsKey(migration.id)) { check(known[migration.id] == migration.checksum) { \"applied migration ${migration.id} checksum mismatch\" }; continue } val oldAuto = conn.autoCommit; conn.autoCommit = false; try { migration.statements.forEach { sql -> conn.createStatement().use { it.execute(sql) } }; conn.prepareStatement(\"INSERT INTO _flash_migrations (id, migration_name, checksum, started_at, finished_at) VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)\").use { ps -> ps.setString(1, migration.id); ps.setString(2, migration.name); ps.setString(3, migration.checksum); ps.executeUpdate() }; conn.commit() } catch (e: Exception) { conn.rollback(); throw e } finally { conn.autoCommit = oldAuto } }\n  }\n}\n")
	return os.WriteFile(filepath.Join(g.Config.Gen.Kotlin.Out, "FlashMigrations.kt"), []byte(w.String()), 0644)
}
