package pygen

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
)

func (g *Generator) generateMigrations() error {
	migrations, err := gencommon.LoadEmbeddedMigrations(g.Config.MigrationsPath)
	if err != nil {
		return fmt.Errorf("load migrations for Python generation: %w", err)
	}
	var w strings.Builder
	w.WriteString("# Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString("MIGRATIONS = [\n")
	for _, m := range migrations {
		w.WriteString(fmt.Sprintf("    {\"id\": %s, \"name\": %s, \"checksum\": %s, \"statements\": [", strconv.Quote(m.ID), strconv.Quote(m.Name), strconv.Quote(m.Checksum)))
		for i, s := range m.Statements {
			if i > 0 {
				w.WriteString(", ")
			}
			w.WriteString(strconv.Quote(s))
		}
		w.WriteString("]},\n")
	}
	w.WriteString("]\n\n")
	if g.Config.Gen.Python.Async {
		w.WriteString("async def FlashInitMigrate(db):\n    \"\"\"Apply embedded migrations without invoking the Flash binary.\"\"\"\n    await db.execute(\"CREATE TABLE IF NOT EXISTS _flash_migrations (id TEXT PRIMARY KEY, checksum TEXT NOT NULL, finished_at TIMESTAMP, migration_name TEXT NOT NULL, started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)\")\n    rows = await db.fetch(\"SELECT id, checksum FROM _flash_migrations WHERE finished_at IS NOT NULL\")\n    known = {row['id']: row['checksum'] for row in rows}\n    for migration in MIGRATIONS:\n        if migration['id'] in known:\n            if known[migration['id']] != migration['checksum']: raise RuntimeError(f\"applied migration {migration['id']} checksum mismatch\")\n            continue\n        async with db.transaction():\n            for statement in migration['statements']: await db.execute(statement)\n            await db.execute(\"INSERT INTO _flash_migrations (id, migration_name, checksum, started_at, finished_at) VALUES ($1, $2, $3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)\", migration['id'], migration['name'], migration['checksum'])\n")
	} else {
		w.WriteString("def FlashInitMigrate(db):\n    \"\"\"Apply embedded migrations without invoking the Flash binary.\"\"\"\n    db.execute(\"CREATE TABLE IF NOT EXISTS _flash_migrations (id TEXT PRIMARY KEY, checksum TEXT NOT NULL, finished_at TIMESTAMP, migration_name TEXT NOT NULL, started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)\")\n    known = {row[0]: row[1] for row in db.execute(\"SELECT id, checksum FROM _flash_migrations WHERE finished_at IS NOT NULL\").fetchall()}\n    for migration in MIGRATIONS:\n        if migration['id'] in known:\n            if known[migration['id']] != migration['checksum']: raise RuntimeError(f\"applied migration {migration['id']} checksum mismatch\")\n            continue\n        for statement in migration['statements']: db.execute(statement)\n        db.execute(\"INSERT INTO _flash_migrations (id, migration_name, checksum, started_at, finished_at) VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)\", (migration['id'], migration['name'], migration['checksum']))\n    db.commit()\n")
	}
	return os.WriteFile(filepath.Join(g.Config.Gen.Python.Out, "migrations.py"), []byte(w.String()), 0644)
}
