# Code generated by FlashORM. DO NOT EDIT.

from typing import Optional, List, Any, Literal
from dataclasses import dataclass
from datetime import datetime, timedelta
from decimal import Decimal

@dataclass
class Preferences:
    """JSON type for column 'preferences'. Parse with: Preferences(**json.loads(row.preferences))"""
    font_size: Optional[int]
    theme: Optional[str]
    notifications: Optional[bool]
    language: Optional[str]

@dataclass
class Metadata:
    """JSON type for column 'metadata'. Parse with: Metadata(**json.loads(row.metadata))"""
    shares: Optional[int]
    bookmarks: Optional[int]
    avg_read_time: Optional[float]
    tags_used: Optional[List[str]]
    views: Optional[int]

@dataclass
class GetUserPrefsRow:
    id: int
    name: str
    email: str
    preferences: Optional[Preferences]

    @classmethod
    def _make_fast(cls, record):
        return cls(
            record['id'],
            record['name'],
            record['email'],
            record['preferences']
        )

@dataclass
class SetUserPrefsRow:
    id: int
    name: str
    preferences: Optional[Preferences]
    updated_at: datetime

    @classmethod
    def _make_fast(cls, record):
        return cls(
            record['id'],
            record['name'],
            record['preferences'],
            record['updated_at']
        )

@dataclass
class GetPostMetaRow:
    id: int
    title: str
    status: Literal['draft', 'published', 'archived']
    metadata: Optional[Metadata]
    user_id: int
    created_at: datetime

    @classmethod
    def _make_fast(cls, record):
        return cls(
            record['id'],
            record['title'],
            record['status'],
            record['metadata'],
            record['user_id'],
            record['created_at']
        )

@dataclass
class ListUsersWithPrefsRow:
    id: int
    name: str
    email: str
    preferences: Optional[Preferences]
    created_at: datetime

    @classmethod
    def _make_fast(cls, record):
        return cls(
            record['id'],
            record['name'],
            record['email'],
            record['preferences'],
            record['created_at']
        )

@dataclass
class ListPostsWithMetaRow:
    id: int
    title: str
    status: Literal['draft', 'published', 'archived']
    view_count: int
    metadata: Optional[Metadata]
    created_at: datetime

    @classmethod
    def _make_fast(cls, record):
        return cls(
            record['id'],
            record['title'],
            record['status'],
            record['view_count'],
            record['metadata'],
            record['created_at']
        )

class Queries:
    def __init__(self, db):
        self.db = db
        self._stmts = {}

    async def get_user_prefs(self, id: int) -> Optional[GetUserPrefsRow]:
        _key = 'get_user_prefs'
        if _key not in self._stmts:
            self._stmts[_key] = """SELECT id, name, email, preferences FROM users WHERE id = $1;"""
        stmt = self._stmts[_key]
        result = await self.db.fetch(stmt, id)
        return GetUserPrefsRow._make_fast(result[0]) if result else None

    async def set_user_prefs(self, preferences: dict, id: int) -> Optional[SetUserPrefsRow]:
        _key = 'set_user_prefs'
        if _key not in self._stmts:
            self._stmts[_key] = """UPDATE users SET preferences = $1, updated_at = NOW() WHERE id = $2 RETURNING id, name, preferences, updated_at;"""
        stmt = self._stmts[_key]
        result = await self.db.fetch(stmt, preferences, id)
        return SetUserPrefsRow._make_fast(result[0]) if result else None

    async def get_post_meta(self, id: int) -> Optional[GetPostMetaRow]:
        _key = 'get_post_meta'
        if _key not in self._stmts:
            self._stmts[_key] = """SELECT id, title, status, metadata, user_id, created_at FROM posts WHERE id = $1;"""
        stmt = self._stmts[_key]
        result = await self.db.fetch(stmt, id)
        return GetPostMetaRow._make_fast(result[0]) if result else None

    async def list_users_with_prefs(self, limit: int) -> List[ListUsersWithPrefsRow]:
        _key = 'list_users_with_prefs'
        if _key not in self._stmts:
            self._stmts[_key] = """SELECT id, name, email, preferences, created_at FROM users ORDER BY created_at DESC LIMIT $1;"""
        stmt = self._stmts[_key]
        result = await self.db.fetch(stmt, limit)
        return [ListUsersWithPrefsRow._make_fast(row) for row in result]

    async def list_posts_with_meta(self, user_id: int) -> List[ListPostsWithMetaRow]:
        _key = 'list_posts_with_meta'
        if _key not in self._stmts:
            self._stmts[_key] = """SELECT id, title, status, view_count, metadata, created_at FROM posts WHERE user_id = $1 AND status = 'published' ORDER BY created_at DESC;"""
        stmt = self._stmts[_key]
        result = await self.db.fetch(stmt, user_id)
        return [ListPostsWithMetaRow._make_fast(row) for row in result]

