package cachegen

import (
	"fmt"
	"strings"

	"github.com/Lumos-Labs-HQ/flash/internal/config"
)

// GenerateJavaCache generates FlashCache.java using Lettuce (Redis)
func GenerateJavaCache(cfg *config.CacheConfig, packageName string) string {
	var w strings.Builder
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	if packageName != "" {
		w.WriteString(fmt.Sprintf("package %s;\n\n", packageName))
	}
	w.WriteString(fmt.Sprintf(`import io.lettuce.core.RedisClient;
import io.lettuce.core.api.sync.RedisCommands;
import io.lettuce.core.ScanArgs;
import io.lettuce.core.ScanCursor;
import io.lettuce.core.KeyScanCursor;
import com.google.gson.Gson;
import java.util.List;
import java.util.Set;

public class FlashCache {
    private static final String REDIS_URL = System.getenv("%s") != null ? System.getenv("%s") : "redis://localhost:6379";
    private static final String PREFIX = "%s";
    private static final RedisClient client = RedisClient.create(REDIS_URL);
    private static final RedisCommands<String, String> commands = client.connect().sync();
    private static final Gson gson = new Gson();

    public static <T> T get(String key, Class<T> clazz) {
        String data = commands.get(PREFIX + ":" + key);
        if (data == null) return null;
        return gson.fromJson(data, clazz);
    }

    public static <T> void set(String key, T value, long ttlSeconds, List<String> tags) {
        String fullKey = PREFIX + ":" + key;
        commands.setex(fullKey, ttlSeconds, gson.toJson(value));
        if (tags != null) {
            for (String tag : tags) {
                commands.sadd(PREFIX + ":tag:" + tag, key);
            }
        }
    }

    public static void del(String key) {
        commands.del(PREFIX + ":" + key);
    }

    public static void purgeByTag(String tag) {
        String tagKey = PREFIX + ":tag:" + tag;
        Set<String> keys = commands.smembers(tagKey);
        for (String k : keys) {
            commands.del(PREFIX + ":" + k);
        }
        commands.del(tagKey);
    }

    public static void purgeByPrefix(String prefix) {
        String pattern = PREFIX + ":" + prefix + "*";
        ScanCursor cursor = ScanCursor.INITIAL;
        do {
            KeyScanCursor<String> result = commands.scan(cursor, ScanArgs.Builder.matches(pattern).limit(100));
            for (String key : result.getKeys()) {
                commands.del(key);
            }
            cursor = result;
        } while (!cursor.isFinished());
    }

    public static void close() {
        client.shutdown();
    }
}
`, cfg.RedisURLEnv, cfg.RedisURLEnv, cfg.Prefix))
	return w.String()
}

// GenerateJavaCacheAccessors generates named cache accessor classes for Java
func GenerateJavaCacheAccessors(caches []*CacheInfo, packageName string) string {
	if len(caches) == 0 {
		return ""
	}

	var w strings.Builder
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	if packageName != "" {
		w.WriteString(fmt.Sprintf("package %s;\n\n", packageName))
	}
	w.WriteString("import java.util.List;\n\n")

	// Generate typed CacheTag enum
	allTags := collectUniqueTags(caches)
	if len(allTags) > 0 {
		w.WriteString("/** Available cache tags for type-safe purging. */\n")
		w.WriteString("public enum CacheTag {\n")
		for i, tag := range allTags {
			suffix := ","
			if i == len(allTags)-1 {
				suffix = ";"
			}
			w.WriteString(fmt.Sprintf("    %s(\"%s\")%s\n", strings.ToUpper(tag), tag, suffix))
		}
		w.WriteString("\n    private final String value;\n")
		w.WriteString("    CacheTag(String value) { this.value = value; }\n")
		w.WriteString("    public String getValue() { return value; }\n\n")
		w.WriteString("    /** Purge all cache entries associated with this tag. */\n")
		w.WriteString("    public void purge() { FlashCache.purgeByTag(value); }\n")
		w.WriteString("}\n\n")
	}

	for _, c := range caches {
		ttlSec := ParseTTL(c.TTL)

		var paramList, keyParts, paramNames []string
		for _, p := range c.KeyParams {
			paramList = append(paramList, fmt.Sprintf("Object %s", p))
			keyParts = append(keyParts, fmt.Sprintf("\" + %s + \"", p))
			paramNames = append(paramNames, p)
		}
		paramStr := strings.Join(paramList, ", ")
		keyExpr := fmt.Sprintf(`"%s:%s"`, c.CacheName, strings.Join(keyParts, ":"))
		if len(keyParts) == 0 {
			keyExpr = fmt.Sprintf(`"%s"`, c.CacheName)
		} else {
			// Build proper Java string concat
			parts := []string{fmt.Sprintf(`"%s:`, c.CacheName)}
			for i, p := range paramNames {
				if i > 0 {
					parts = append(parts, `":"`)
				}
				parts = append(parts, fmt.Sprintf(`" + %s + "`, p))
			}
			parts = append(parts, `"`)
			keyExpr = strings.Join(parts, "")
			keyExpr = fmt.Sprintf(`"%s:" + %s`, c.CacheName, strings.Join(paramNames, ` + ":" + `))
		}

		tagsLiteral := "null"
		if len(c.Tags) > 0 {
			quoted := make([]string, len(c.Tags))
			for i, t := range c.Tags {
				quoted[i] = fmt.Sprintf(`"%s"`, t)
			}
			tagsLiteral = fmt.Sprintf("List.of(%s)", strings.Join(quoted, ", "))
		}

		w.WriteString(fmt.Sprintf("public class %s {\n", c.CacheName))
		w.WriteString(fmt.Sprintf("    public static <T> T get(%s, Class<T> clazz) {\n", paramStr))
		w.WriteString(fmt.Sprintf("        return FlashCache.get(%s, clazz);\n", keyExpr))
		w.WriteString("    }\n\n")
		w.WriteString(fmt.Sprintf("    public static <T> void set(%s, T value) {\n", paramStr))
		w.WriteString(fmt.Sprintf("        FlashCache.set(%s, value, %dL, %s);\n", keyExpr, ttlSec, tagsLiteral))
		w.WriteString("    }\n\n")
		w.WriteString(fmt.Sprintf("    public static void del(%s) {\n", paramStr))
		w.WriteString(fmt.Sprintf("        FlashCache.del(%s);\n", keyExpr))
		w.WriteString("    }\n\n")
		w.WriteString("    public static void purge() {\n")
		w.WriteString(fmt.Sprintf("        FlashCache.purgeByPrefix(\"%s:\");\n", c.CacheName))
		w.WriteString("    }\n")
		w.WriteString("}\n\n")
	}
	return w.String()
}
