package cachegen

import (
	"fmt"
	"strings"

	"github.com/Lumos-Labs-HQ/flash/internal/config"
)

// GeneratePythonCache generates the cache.py file
func GeneratePythonCache(cfg *config.CacheConfig) string {
	var w strings.Builder
	w.WriteString("# Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString(fmt.Sprintf(`import os
import json
from typing import TypeVar, Optional, List, Any
from dataclasses import asdict, is_dataclass
import redis

T = TypeVar("T")

_REDIS_URL = os.environ.get("%s", "redis://localhost:6379")
_PREFIX = "%s"
_client = redis.from_url(_REDIS_URL, decode_responses=True)


class FlashCache:
    """Redis-backed cache for FlashORM queries."""

    def get(self, key: str) -> Optional[Any]:
        data = _client.get(f"{_PREFIX}:{key}")
        if data is None:
            return None
        return json.loads(data)

    def set(self, key: str, value: Any, ttl_seconds: int, tags: Optional[List[str]] = None) -> None:
        full_key = f"{_PREFIX}:{key}"
        data = json.dumps(asdict(value) if is_dataclass(value) else value)
        _client.setex(full_key, ttl_seconds, data)
        for tag in (tags or []):
            _client.sadd(f"{_PREFIX}:tag:{tag}", key)

    def delete(self, key: str) -> None:
        _client.delete(f"{_PREFIX}:{key}")

    def purge_by_tag(self, tag: str) -> None:
        tag_key = f"{_PREFIX}:tag:{tag}"
        keys = _client.smembers(tag_key)
        for k in keys:
            _client.delete(f"{_PREFIX}:{k}")
        _client.delete(tag_key)

    def purge_by_prefix(self, prefix: str) -> None:
        pattern = f"{_PREFIX}:{prefix}*"
        for key in _client.scan_iter(match=pattern, count=100):
            _client.delete(key)

    def close(self) -> None:
        _client.close()


cache = FlashCache()
`, cfg.RedisURLEnv, cfg.Prefix))
	return w.String()
}

// GeneratePythonCacheAccessors generates named cache accessors for Python
func GeneratePythonCacheAccessors(caches []*CacheInfo) string {
	if len(caches) == 0 {
		return ""
	}

	var w strings.Builder
	w.WriteString("# Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString("from typing import Optional, Any\nfrom enum import Enum\nfrom .cache import cache\n\n")

	// Generate typed CacheTag enum
	allTags := collectUniqueTags(caches)
	if len(allTags) > 0 {
		w.WriteString("class CacheTag(str, Enum):\n")
		w.WriteString("    \"\"\"Available cache tags for type-safe purging.\"\"\"\n")
		for _, tag := range allTags {
			w.WriteString(fmt.Sprintf("    %s = \"%s\"\n", strings.ToUpper(tag), tag))
		}
		w.WriteString("\n\n")
		w.WriteString("def purge_tag(tag: CacheTag) -> None:\n")
		w.WriteString("    \"\"\"Purge all cache entries associated with a tag.\"\"\"\n")
		w.WriteString("    cache.purge_by_tag(tag.value)\n\n\n")
	}

	for _, c := range caches {
		ttlSec := ParseTTL(c.TTL)
		className := c.CacheName

		var paramList, keyParts []string
		for _, p := range c.KeyParams {
			paramList = append(paramList, p)
			keyParts = append(keyParts, fmt.Sprintf("{%s}", p))
		}
		paramStr := strings.Join(paramList, ", ")
		keyExpr := fmt.Sprintf(`f"%s:%s"`, className, strings.Join(keyParts, ":"))
		if len(keyParts) == 0 {
			keyExpr = fmt.Sprintf(`"%s"`, className)
		}

		tagsLiteral := "None"
		if len(c.Tags) > 0 {
			quoted := make([]string, len(c.Tags))
			for i, t := range c.Tags {
				quoted[i] = fmt.Sprintf(`"%s"`, t)
			}
			tagsLiteral = fmt.Sprintf("[%s]", strings.Join(quoted, ", "))
		}

		w.WriteString(fmt.Sprintf("class %s:\n", className))
		w.WriteString("    @staticmethod\n")
		w.WriteString(fmt.Sprintf("    def get(%s) -> Optional[Any]:\n", paramStr))
		w.WriteString(fmt.Sprintf("        return cache.get(%s)\n\n", keyExpr))
		w.WriteString("    @staticmethod\n")
		w.WriteString(fmt.Sprintf("    def set(%s, value: Any) -> None:\n", paramStr))
		w.WriteString(fmt.Sprintf("        cache.set(%s, value, %d, %s)\n\n", keyExpr, ttlSec, tagsLiteral))
		w.WriteString("    @staticmethod\n")
		w.WriteString(fmt.Sprintf("    def delete(%s) -> None:\n", paramStr))
		w.WriteString(fmt.Sprintf("        cache.delete(%s)\n\n", keyExpr))
		w.WriteString("    @staticmethod\n")
		w.WriteString("    def purge() -> None:\n")
		w.WriteString(fmt.Sprintf("        cache.purge_by_prefix(\"%s:\")\n\n\n", className))
	}
	return w.String()
}
