package cachegen

import (
	"fmt"
	"strings"

	"github.com/Lumos-Labs-HQ/flash/internal/config"
)

// GenerateRustCache generates cache.rs using the redis crate
func GenerateRustCache(cfg *config.CacheConfig) string {
	var w strings.Builder
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n")
	w.WriteString("#![allow(dead_code)]\n\n")
	w.WriteString(fmt.Sprintf(`use redis::{Client, Commands};
use serde::{Serialize, de::DeserializeOwned};
use std::time::Duration;

/// Redis-backed cache for FlashORM queries.
pub struct FlashCache {
    client: Client,
    prefix: String,
}

impl FlashCache {
    pub fn new() -> Self {
        let url = std::env::var("%s").unwrap_or_else(|_| "redis://localhost:6379".to_string());
        let client = Client::open(url).expect("Failed to connect to Redis");
        Self {
            client,
            prefix: "%s".to_string(),
        }
    }

    pub fn get<T: DeserializeOwned>(&self, key: &str) -> Option<T> {
        let mut conn = self.client.get_connection().ok()?;
        let full_key = format!("{}:{}", self.prefix, key);
        let data: Option<String> = conn.get(&full_key).ok()?;
        data.and_then(|d| serde_json::from_str(&d).ok())
    }

    pub fn set<T: Serialize>(&self, key: &str, value: &T, ttl: Duration, tags: &[&str]) {
        if let Ok(mut conn) = self.client.get_connection() {
            let full_key = format!("{}:{}", self.prefix, key);
            if let Ok(data) = serde_json::to_string(value) {
                let _: () = conn.set_ex(&full_key, &data, ttl.as_secs()).unwrap_or(());
                for tag in tags {
                    let tag_key = format!("{}:tag:{}", self.prefix, tag);
                    let _: () = conn.sadd(&tag_key, key).unwrap_or(());
                }
            }
        }
    }

    pub fn del(&self, key: &str) {
        if let Ok(mut conn) = self.client.get_connection() {
            let full_key = format!("{}:{}", self.prefix, key);
            let _: () = conn.del(&full_key).unwrap_or(());
        }
    }

    pub fn purge_by_tag(&self, tag: &str) {
        if let Ok(mut conn) = self.client.get_connection() {
            let tag_key = format!("{}:tag:{}", self.prefix, tag);
            let keys: Vec<String> = conn.smembers(&tag_key).unwrap_or_default();
            for k in &keys {
                let full_key = format!("{}:{}", self.prefix, k);
                let _: () = conn.del(&full_key).unwrap_or(());
            }
            let _: () = conn.del(&tag_key).unwrap_or(());
        }
    }

    pub fn purge_by_prefix(&self, prefix: &str) {
        if let Ok(mut conn) = self.client.get_connection() {
            let pattern = format!("{}:{}*", self.prefix, prefix);
            let keys: Vec<String> = redis::cmd("KEYS").arg(&pattern).query(&mut conn).unwrap_or_default();
            for key in &keys {
                let _: () = conn.del(key).unwrap_or(());
            }
        }
    }
}

lazy_static::lazy_static! {
    pub static ref CACHE: FlashCache = FlashCache::new();
}
`, cfg.RedisURLEnv, cfg.Prefix))
	return w.String()
}

// GenerateRustCacheAccessors generates named cache accessor structs for Rust
func GenerateRustCacheAccessors(caches []*CacheInfo) string {
	if len(caches) == 0 {
		return ""
	}

	var w strings.Builder
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n")
	w.WriteString("#![allow(dead_code)]\n\n")
	w.WriteString("use super::cache::CACHE;\n")
	w.WriteString("use serde::{Serialize, de::DeserializeOwned};\n")
	w.WriteString("use std::time::Duration;\n\n")

	for _, c := range caches {
		ttlSec := ParseTTL(c.TTL)
		structName := c.CacheName

		var paramList, keyParts []string
		for _, p := range c.KeyParams {
			paramList = append(paramList, fmt.Sprintf("%s: impl std::fmt::Display", p))
			keyParts = append(keyParts, "{}")
		}
		paramStr := strings.Join(paramList, ", ")
		keyFormat := structName + ":" + strings.Join(keyParts, ":")
		if len(keyParts) == 0 {
			keyFormat = structName
		}

		// Build format args
		var formatArgs string
		if len(c.KeyParams) > 0 {
			formatArgs = ", " + strings.Join(c.KeyParams, ", ")
		}

		tagsLiteral := "&[]"
		if len(c.Tags) > 0 {
			quoted := make([]string, len(c.Tags))
			for i, t := range c.Tags {
				quoted[i] = fmt.Sprintf(`"%s"`, t)
			}
			tagsLiteral = fmt.Sprintf("&[%s]", strings.Join(quoted, ", "))
		}

		w.WriteString(fmt.Sprintf("pub struct %s;\n\n", structName))
		w.WriteString(fmt.Sprintf("impl %s {\n", structName))

		// get
		w.WriteString(fmt.Sprintf("    pub fn get<T: DeserializeOwned>(%s) -> Option<T> {\n", paramStr))
		w.WriteString(fmt.Sprintf("        let key = format!(\"%s\"%s);\n", keyFormat, formatArgs))
		w.WriteString("        CACHE.get(&key)\n")
		w.WriteString("    }\n\n")

		// set
		setParams := paramStr
		if setParams != "" {
			setParams += ", "
		}
		w.WriteString(fmt.Sprintf("    pub fn set<T: Serialize>(%svalue: &T) {\n", setParams))
		w.WriteString(fmt.Sprintf("        let key = format!(\"%s\"%s);\n", keyFormat, formatArgs))
		w.WriteString(fmt.Sprintf("        CACHE.set(&key, value, Duration::from_secs(%d), %s);\n", ttlSec, tagsLiteral))
		w.WriteString("    }\n\n")

		// del
		w.WriteString(fmt.Sprintf("    pub fn del(%s) {\n", paramStr))
		w.WriteString(fmt.Sprintf("        let key = format!(\"%s\"%s);\n", keyFormat, formatArgs))
		w.WriteString("        CACHE.del(&key);\n")
		w.WriteString("    }\n\n")

		// purge
		w.WriteString("    pub fn purge() {\n")
		w.WriteString(fmt.Sprintf("        CACHE.purge_by_prefix(\"%s:\");\n", structName))
		w.WriteString("    }\n")
		w.WriteString("}\n\n")
	}
	return w.String()
}
